### ISSUE TITLE
fixes

### ISSUE THREAD

**Issue by sshoecraft** [christgau/wsdd#10]
updated makefile (only affected lines shown)

ifneq (,$(wildcard /etc/systemd/system/.))
        install -o root -g root etc/systemd/wsdd.service /etc/systemd/system
else
        install -o root -g root etc/rc.d/wsdd /etc/init.d
endif

In etc/systemd/wsdd.service, change /usr/bin to /usr/local/bin (or change the install above to /usr/bin)

ExecStart=/usr/local/bin/wsdd --shortlog

**Comment by christgau** [comment]
Whoops 😉 There is no Makefile in the repository. Are you sure you hit the correct Github project? You may also consider to open a pull request.

**Comment by christgau** [comment]
No Makefile, no response, no fix for this issue.
