### ISSUE TITLE
Systemd Unit-File Fails to Load When Using Group/User Nobody.

### ISSUE THREAD

**Issue by mikecummings34** [christgau/wsdd#101]
It seems that when running Debian-10 on proxmox in lxc, systemctl fails to start the wsdd service due to a user issue. I have not tested if this is the case with other distros, or environments but it seems pretty straight forward.

lxc-pve: 4.0.6-2
debian 10.7

> wsdd.service - Web Services Dynamic Discovery host daemon
   Loaded: loaded (/etc/systemd/system/wsdd.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2021-04-21 02:40:06 UTC; 4s ago
  Process: 1182 ExecStart=/usr/bin/wsdd --shortlog -d flowdomain.com (code=exited, status=217/USER)
 Main PID: 1182 (code=exited, status=217/USER)

> Apr 21 02:40:06 yougotserved systemd[1]: Started Web Services Dynamic Discovery host daemon.
Apr 21 02:40:06 yougotserved systemd[1182]: wsdd.service: Failed to determine user credentials: No such process
Apr 21 02:40:06 yougotserved systemd[1182]: wsdd.service: Failed at step USER spawning /usr/bin/wsdd: No such process
Apr 21 02:40:06 yougotserved systemd[1]: wsdd.service: Main process exited, code=exited, status=217/USER
Apr 21 02:40:06 yougotserved systemd[1]: wsdd.service: Failed with result 'exit-code'.

**Comment by christgau** [comment]
> It seems that when running Debian-10 on proxmox in lxc, systemctl fails to start the wsdd service due to a user issue. I have not tested if this is the case with other distros, or environments but it seems pretty straight forward.

Other users reported scenarios where nobody (nogroup) was successfully used on Ubuntu (which is Debian-based) and RHEL. I searched the web for error the error message "Failed to determine user credentials: No such process". It appears that it might be systemd-related and can be solved by `systemctl daemon-reexec` which basically restarts systemd without a reboot, but I am unable to test and reproduce the issue. 

In addition error 217 appears to indicate that the user did not exist on the system. Please ensure that the user/group specified in the unit file do actually exist on the system.
