### ISSUE TITLE
Does wsdd support hirsute distro?

### ISSUE THREAD

**Issue by Spectroxx** [christgau/wsdd#118]
Does wsdd support hirsute? I managed to get it running on popOS. Samba is configured properly, it's just my linux machine isn't displaying on windows? My windows machine has SMB enabled, I'm not sure what's wrong.

I followed the exact same steps when I used this on Ubuntu 20.04 LTS

**Comment by christgau** [comment]
I haven't tested wsdd on Ubuntu 21.04 (Hirsute Hippo), but it should not make a difference compared to other Linux distros. If you encouter problems, you may start wsdd on the command line and monitor the output while no other instance is running on the machine. If you see lines with 'Probe', 'Resolve', and 'POST' if you do a refresh in the Windows Explorer, it would good. If not, please post the output... You may also check the firewall.

**Comment by Spectroxx** [comment]
Alright, will do. I'll post what I find.

**Comment by Spectroxx** [comment]
So I checked the firewall, there's no issues with that.  
```
sudo service wsdd status
● wsdd.service - Web Services Dynamic Discovery host daemon
     Loaded: loaded (/etc/systemd/system/wsdd.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2021-07-26 18:07:50 EDT; 14s ago
   Main PID: 8744 (python3)
      Tasks: 1 (limit: 9307)
     Memory: 15.5M
     CGroup: /system.slice/wsdd.service
             └─8744 python3 /usr/bin/wsdd --shortlog

Jul 26 18:07:50 julien systemd[1]: Started Web Services Dynamic Discovery host daemon.
Jul 26 18:07:51 julien wsdd[8744]: WARNING: no interface given, using all interfaces
```
It seems to be running fine without issue. Could it be a windows 11 problem...maybe?

**Comment by christgau** [comment]
Thanks, but it's actually not really what I wanted 😉. Sorry if was unprecise here, so let's be more accurate. Please do the following:

1. Stop the running wsdd instance using `systemctl stop wsdd`
2. Start wsdd on the command line as follows: `wsdd -vvv`
3. Do a refresh in the network view of Windows' Explorer. 
4. After the refresh has finished, copy the output of wsdd an post it here. You may obfuscate IP addresses, although they should be from private networks anyways. 

It's interesting that you are using Windows 11. I haven't tested it yet. Maybe there was a change on the Windows side that prevents wsdd from working correctly. Let's dig into it by following the above steps first...

**Comment by christgau** [comment]
I've just tested a fresh Ubuntu Server 21.04 installation together with a Win10 machine. Everything worked as expected...

**Comment by christgau** [comment]
I close the issue as it seems the original question has been answered: wsdd runs on Hirsute and its successor. If there is an issue with Windows 11 it deserves a new issue.
