### ISSUE TITLE
Gentoo ebuild/package 

### ISSUE THREAD

**Issue by Gatak** [christgau/wsdd#12]
Hello,

I was wondering if you would consider making wsdd available as a Gentoo ebuild. Currently there is no wsd daemon in Gentoo and I think a lot of people would find your wsdd very useful.

Thank you.

**Comment by christgau** [comment]
Thanks for that suggestion. Sounds like a nice side-project for a long-time Gentoo user who occasionally considered to dig into package maintenance. 😉 It deserves a dedicated repo aside from this upstream project. Updates follow here when there is considerable progress - or not.

**Comment by Gatak** [comment]
:thumbsup: You're right. Now, we just have to find such a user :sunglasses:

**Comment by Gatak** [comment]
I made an initial ebuild at https://github.com/Gatak/wsdd-ebuild
This has only been tested on my own system, amd64 arch with Python 3.6, but works so far :)

**Comment by christgau** [comment]
Nice! I should remind myself that irony does not always work well on the web in written form 😉 I started writing an ebuild on Monday. It's a little different from yours but we can conbine our efforts. I'll make that one public in a bit.

**Comment by Gatak** [comment]
I thought you meant something like that, but I was not sure. I thought to make a pull request to gentoo with a proxy maintainer. What do you think? https://github.com/Gatak/gentoo/tree/wsdd/net-misc/wsdd

**Comment by christgau** [comment]
> I thought you meant something like that, but I was not sure. I thought to make a pull request to gentoo with a proxy maintainer. What do you think? https://github.com/Gatak/gentoo/tree/wsdd/net-misc/wsdd

In principle, its a nice idea to have a distribution package, but let us consolidate our ebuild efforts first before we send something to the distro guys. 

I published my (very) first attempt of an ebuild/overlay tree in https://github.com/christgau/wsdd-gentoo. Any further discussion, issues or PRs concerning the ebuild should be done over there.
