### ISSUE TITLE
Samba server on Ubuntu 20.04 not discoverable by Ubuntu 20/21 desktops

### ISSUE THREAD

**Issue by Erriez** [christgau/wsdd#126]
Thanks for creating this project. I've the following setup:

Ubuntu server 20.04 running Samba server + wsdd, no issues.
Windows 10 shows the Samba server with Windows Explorer | Network.
Ubuntu 20/21 desktops don't show the Samba sever with Nautilus | Other Locations | Network.

The Samba sever is discoverable by Ubuntu desktops by installing `cups` on the Samba server:

```bash
# Install cups on Samba server:
$ sudo apt install cups
```

Maybe something to mention in the `README.md`, or did I configure the Samba server incorrectly?

**Comment by christgau** [comment]
> Windows 10 shows the Samba server with Windows Explorer | Network.

Great. That's what wsdd was designed for...

>  Ubuntu 20/21 desktops don't show the Samba sever with Nautilus | Other Locations | Network.

... opposite to this. 

The purpose of wsdd is not to make Samba hosts appear in Nautilus. Thus, this is a won't fix. AFAIK there is a avahi support in Samba and maybe that's a starting for you here. A quick googling led me to this blog post: https://kimathir.wordpress.com/2021/07/14/samba-avahi-ubuntu/

> The Samba sever is discoverable by Ubuntu desktops by installing cups on the Samba server:

Might be avahi/bonjour as well, but I'm pretty sure that cups announces the host as print server and not as a file share.

**Comment by Erriez** [comment]
Thanks for your comments. I'll investigate this further.
