### ISSUE TITLE
support for /etc/conf.d with openrc

### ISSUE THREAD

**Issue by Gatak** [christgau/wsdd#13]
It would be nice if /etc/conf.d/wsdd was supported to set command arguments to wsdd

Add:
/etc/conf.d/wsdd
`WSDD_OPTS="-i eth1"`

Change 
/etc/init.d/wsdd
`OPTS="-w ${GROUP} ${OPTS}" ` to `OPTS="-w ${GROUP} ${WSDD_OPTS}"`

I am not sure how to do this with systemd.

**Comment by christgau** [comment]
Yeah, I considered that as well when I wrote the ebuild. `WSDD_OPTS` is the minimum we can do, but I thought that adding an option for the user:group under which the service will be running would be good idea as well.

**Comment by Gatak** [comment]
Yes, that would be nice too. :)
