### ISSUE TITLE
Install via apt on Ubuntu 22.04 Jammy Jellyfish

### ISSUE THREAD

**Issue by HappyMan4** [christgau/wsdd#137]
Hi there,

when trying to install wsdd via apt on Ubuntu 22.04 LTS (Jammy Jellyfish) there is an error stating a 404 and that there is no release file.
Can I use the 20.04 Focal Fossa version as well when replacing "jammy" with "focal" in /etc/apt/sources.list.d/wsdd.list ?

Here is the log output:

> root@myserver:~ # update
> Hit:1 http://de.archive.ubuntu.com/ubuntu jammy InRelease
> Get:2 http://de.archive.ubuntu.com/ubuntu jammy-updates InRelease [109 kB]
> Hit:3 http://de.archive.ubuntu.com/ubuntu jammy-backports InRelease
> Get:4 http://de.archive.ubuntu.com/ubuntu jammy-security InRelease [99.4 kB]
> Ign:5 https://pkg.ltec.ch/public jammy InRelease
> Err:6 https://pkg.ltec.ch/public jammy Release
>   404  Not Found [IP: 95.143.48.181 443]
> Get:7 http://de.archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [28.4 kB]
> Get:8 http://de.archive.ubuntu.com/ubuntu jammy-updates/main Translation-en [8,240 B]
> Get:9 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [8,816 B]
> Get:10 http://de.archive.ubuntu.com/ubuntu jammy-updates/universe Translation-en [3,552 B]
> Get:11 http://de.archive.ubuntu.com/ubuntu jammy-security/main amd64 Packages [21.1 kB]
> Get:12 http://de.archive.ubuntu.com/ubuntu jammy-security/main Translation-en [6,720 B]
> Get:13 http://de.archive.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [20.3 kB]
> Get:14 http://de.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [3,692 B]
> Reading package lists... Done
> E: The repository 'https://pkg.ltec.ch/public jammy Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> root@myserver:~ #

**Comment by christgau** [comment]
AFAIK, wsdd has landed in the Universe repository of Jammy: https://packages.ubuntu.com/jammy/net/wsdd Thus, there is no need for the community provided packages in your case - at least from my perspective.

**Comment by HappyMan4** [comment]
You're right, I didn't expect the package in universe. Thanks a lot for your reply!
