### ISSUE TITLE
Windows 7 cannot recognise Mint shares: Is this the tool for that?

### ISSUE THREAD

**Issue by eband** [christgau/wsdd#141]
Due to a new update to Samba, my Windows 7 can no longer recognise my Mint 20.3 shares.

My Mint computer, however, can access my Windows 7 shares.

When I try to connect to my Mint shares using my Windows 7 computer, get an Unspecified Error (0x80004005).

Will this tool help with that?

**Comment by christgau** [comment]
> Due to a new update to Samba, my Windows 7 can no longer recognise my Mint 20.3 shares.

What do you mean by "recognise". Are you able to see the host? Or are you not able to see the _shares_ after you opened the host. The latter is out of wsdd's scope. The former is related to wsdd. You need to clearify what you would expect and what is not working.

BTW: Windows 7 is not supported by Microsoft for more than two years. You may consider an update.

> My Mint computer, however, can access my Windows 7 shares.

This has nothing to do with wsdd.

> When I try to connect to my Mint shares using my Windows 7 computer, get an Unspecified Error (0x80004005).

_Connecting_ to Samba shares from a Windows PC is a Samba issue. It is not related to wsdd. 

The primary/sole purpose of wsdd is to show an icon for the Samba host in the Network view of Windows Explorer. Everything "behind" that is out of wsdd's scope.

I am closing this issue as it appears to be unrelated to wsdd. If this is not the case, feel free to reopen it.
