### ISSUE TITLE
[0.7.0 Debian] incorrect installed service permissions

### ISSUE THREAD

**Issue by malventano** [christgau/wsdd#148]
Recommed default install `/lib/systemd/system/wsdd.service` permissions be set to 644 vs. 660.
- 644 is the default for installed services.
- 660 results in errors logged when user enables the service.

Debug:
- Noted in journalctl upon wsdd install (when issuing `systemctl enable wsdd`):
`Configuration file /lib/systemd/system/wsdd.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.`
- Disabled wsdd service and noted permissions of service with stat:
`Access: (0660/-rw-rw----)`
- Changed permissions to match other system services:
`Access: (0644/-rw-r--r--)`
- Re-enabled wsdd and noted error no longer appears in log.

[Related](https://opendev.org/openstack/tripleo-ansible/commit/b7891538819939b1be24394b9b24fe7edd08791f)

**Comment by christgau** [comment]
I assume this issue is related to the user-contributed Debian packages? Or is it a problem with the package from Debian testing/unstable?!

**Comment by malventano** [comment]
The package came from `https://pkg.ltec.ch/public/`, which I assume is user maintained? I would have pulled straight from the git but the manual installation instructions were no longer present in the readme.

**Comment by christgau** [comment]
> The package came from `https://pkg.ltec.ch/public/`, which I assume is user maintained? 

Yes, that's the user maintained package. So the issue is related to #19.

> I would have pulled straight from the git but the manual installation instructions were no longer present in the readme.

There have never been instructions on how to manually install wsdd for systemd. The only steps to put the script in a custom location and example systemd files were and are provided.

**Comment by christgau** [comment]
Since there are official packages and #19 is closed now, this issue will not be worked on anymore.
