### ISSUE TITLE
wsdd not working on debian bullseye with kernel 4.1

### ISSUE THREAD

**Issue by Ghilteras** [christgau/wsdd#150]
I have wsdd running, yet I cannot discover my linux box using a network scan neither from Windows 10 nor from Android (both phone and nvidia Shield). Do I need to add a special option to make network discovery possible?

**Comment by christgau** [comment]
I am not aware if Android (with whatever apps installed) actually scans for WSD devices and how it recognizes them in detail. Wsdd was built to be compatible with Windows. Up to now, Android has never been a target. If you have more information on your Android setup, I may consider to look into details. Until then such support is out of scope and that part of the issue a "won't fix"

Concerning the Windows-related issue: Could you please start wsdd with `-v` on the command line (stop any other running instance of wsdd before). After wsdd has been launched issue a refresh in Explorer's "Network" view. When you the refresh, you should see messages from wsdd on the terminal like 

```
INFO(pid 15163): 192.168.2.10 - - "POST /abcdef12-3456-7890-bb48-2f976fe4dd67 HTTP/1.1" 200 -
```

If not, please check your firewall settings. Refer to the man page or the README for details.
In case this does not help, post the terminal output of wsdd here for further analysis. You may anonymize IP addresses in the output.

**Comment by Ghilteras** [comment]
Thanks @christgau for the clarification. Please close the issue and won't fix is ok. I did not realize that Android was out of the scope of WSDD. Apologies. I am not sure where to look for this, but this is clearly the wrong place. Basically I have a Debian Openmediavault box and my phone/Shield cannot discover it. There must be something I should be able to setup on the Linux side to make it advertise on the network though.

**Comment by christgau** [comment]
>  Please close the issue and won't fix is ok.

Ok.

> There must be something I should be able to setup on the Linux side to make it advertise on the network though.

Take a look at Zeroconf/Avahi and/or SSDP.
