### ISSUE TITLE
Unable to add wsdd repository to the apt repo list

### ISSUE THREAD

**Issue by chayote23** [christgau/wsdd#155]
While attempting to install wsdd to a Ubuntu 20.04 machine, I was not able to add the wsdd repository to the apt repo list.

```
$ sudo wget -O- https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key | gpg --dearmour > /usr/share/keyrings/wsdd.gpg
bash: /usr/share/keyrings/wsdd.gpg: Permission denied
--2022-09-11 06:34:56--  https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key
Resolving pkg.ltec.ch (pkg.ltec.ch)... 95.143.48.181
Connecting to pkg.ltec.ch (pkg.ltec.ch)|95.143.48.181|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1686 (1.6K) [application/pgp-keys]
Saving to: ‘STDOUT’
                                           0%[                                                                                              ]       0  --.-KB/s    in 0s      
Cannot write to ‘-’ (Success).
Ubuntu20.04:~/Downloads/wsdd-master/wsdd-master/etc/systemd$ echo "deb [signed-by=/usr/share/keyrings/wsdd.gpg] https://pkg.ltec.ch/public/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/wsdd.list
bash: /etc/apt/sources.list.d/wsdd.list: Permission denied
```

**Comment by christgau** [comment]
The usage of `sudo` is wrong and there is no issue w.r.t wsdd. Please read the output of the commands carefully and take note of the error messages.

**Comment by chayote23** [comment]
I tried again without sudo but observed a similar result:

```
wget -O- https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key | gpg --dearmour > /usr/share/keyrings/wsdd.gpg
bash: /usr/share/keyrings/wsdd.gpg: Permission denied
--2022-09-21 05:18:37--  https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key
Resolving pkg.ltec.ch (pkg.ltec.ch)... 95.143.48.181
Connecting to pkg.ltec.ch (pkg.ltec.ch)|95.143.48.181|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1686 (1.6K) [application/pgp-keys]
Saving to: ‘STDOUT’
-  0%[   ]       0  --.-KB/s    in 0s      
Cannot write to ‘-’ (Success).
```

**Comment by christgau** [comment]
>>> ```
>>> $ sudo wget -O- https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key | gpg --dearmour > /usr/share/keyrings/wsdd.gpg
>>> bash: /usr/share/keyrings/wsdd.gpg: Permission denied
>>> ```
>> The usage of sudo is wrong 
> 
> I tried again without sudo but observed a similar result:

I didn't say that using sudo is wrong here, I just (wanted to) say the way you use it is wrong. I'm sorry if you got my answer wrong. 

Please take a look at the error message and reason about for what purpose you actually want to use sudo. Do you really need to fetch some internet content with root privileges or convert a GPG key in plain text representation to the native format with raised permissions?
