### ISSUE TITLE
cant install wsdd

### ISSUE THREAD

**Issue by C74K** [christgau/wsdd#157]
sudo apt update
Stary:1 http://pl.archive.ubuntu.com/ubuntu xenial InRelease
Pobieranie:2 http://pl.archive.ubuntu.com/ubuntu xenial-updates InRelease [99,8 kB]
Stary:3 http://security.ubuntu.com/ubuntu xenial-security InRelease
Ign.:4 https://pkg.ltec.ch/public xenial InRelease
Pobieranie:5 http://pl.archive.ubuntu.com/ubuntu xenial-backports InRelease [97,4 kB]
Błąd:6 https://pkg.ltec.ch/public xenial Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Czytanie list pakietów... Gotowe
E: The repository 'https://pkg.ltec.ch/public xenial Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by christgau** [comment]
AFAIK, Xenial is not supported anymore, so I wouldn't be surprised that the package repo does not provide a wsdd package. Maybe you should consider an update. Also, I'm not sure if Xenial actually brings the required Python version (3.7) with it..

**Comment by C74K** [comment]
python3.7 installed but cant install wsdd

**Comment by christgau** [comment]
As said, Xenical support (in general, to be a little more precise) has ended. From my point of view it therefore makes no sense to still provide or even create new packages for that distro. I therefore, consider this as a won't fix, although I personally/this repo do not provide packages. 

Putting this aside, you can still install wsdd manually. Refer to the README for the tiny details.

**Comment by fxrb** [comment]
This is most likely related the the error message reported:

> Błąd:6 https://pkg.ltec.ch/public xenial Release
server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Czytanie list pakietów... Gotowe

Once you manage to fix this error things could be working just fine.
Having said that, @christgau  is right: you should definitely consider upgrading your system.
