### ISSUE TITLE
Could not discover Windows 10 host

### ISSUE THREAD

**Issue by owl-from-hogvarts** [christgau/wsdd#158]
Host it discovered via phone (Huawei) and another windows 10 pc.
Linux host is visible from all devices in the network (win10 pc and phone see it)

What other details can I provide?

**Comment by christgau** [comment]
I'm afraid, but IMO that's a very vague description. I understand that you want to discover your Windows 10 host from Linux. Are you using wsdd directly? What commands do you use?

**Comment by owl-from-hogvarts** [comment]
I had tried launching `wsdd` by hand via `wsdd -D -o -v` and it has shown  win10 pc as intended. So the problem was that wsdd prints discovered hosts on command line only when `-v` is specified.
