### ISSUE TITLE
Netatalk with wsdd

### ISSUE THREAD

**Issue by Xielipton** [christgau/wsdd#163]
The afp conflict between wsdd and netatalk. I built timemachine sever on samba on ubuntu server 22, but after restarting the MacBook, I can find the ubuntu samba host, but it can't connect. After uninstalling netatalk, it will be restored. It's a strange problem that I haven't slept all night.

**Comment by christgau** [comment]
I am not sure if I get this correct, but I don't actually see how wsdd conflicts here with whatever. Please note that wsdd has in principle nothing to do with the connectivity to Samba. Simplified, wsdd only replies to the question "Is there a host that offers a Samba service out there" which is asked by clients like your MacBook.  The reply is then something like "Yep, the host named X over here is offering Samba". As soon as click "X" in your file/network browser you try to connect to the Samba service. Note that a running wsdd instance does not imply that Samba is running on that host as well. They are not depending on each other from a pure technical point of view. 

If you cannot connect to the announced Samba service on X there are two possibilities

1. Samba is not running 
2. Your MacBook cannot resolve the hostname announced by wsdd or the resolution results in a wrong IP address. 

I assume the latter is the case. Please check that your name resolution works when netatalk is installed/running. I see that for Ubuntu the netatalk package recommends the avahi daemon which offers a kind of name resolution. Could it be that avahi gets installed with netatalk but is not configured correctly and thus prevents successful name resolution? 

Nevertheless, as long as there is no clear description what wsdd is doing wrong here, I am closing the issue. Feel free to provide a more precise description and reopen the issue.
