### ISSUE TITLE
wsdd discover but kde dolphin does not show shared folder

### ISSUE THREAD

**Issue by Mario156090** [christgau/wsdd#191]
Hello, I'm using this tool and have a problem, I can't watch the Windows folders shared by Windows 11 in another computer. I'm using wsdd in discover mode and my firewalls are down.

I watch the wsdd log and see the Windows 11 computer name and IP discovered.

![image](https://github.com/christgau/wsdd/assets/47507975/c7de9662-6341-4925-b5c9-a780751f7e45)

After if I open kde dolphin and check smbshares I can't watch the computer from Windows 11.

![image](https://github.com/christgau/wsdd/assets/47507975/70882b84-ab3b-4702-aac8-2b6a52cbd779)

So the question is:

do I need to do some thing more or this a kde dolphin problem?

**Comment by christgau** [comment]
> I watch the wsdd log and see the Windows 11 computer name and IP discovered.

So, wsdd does what it is supposed to do (in discovery mode).

> After if I open kde dolphin and check smbshares I can't watch the computer from Windows 11.

That's likely a Dolphin issue. I have no idea what it is doing under the hood, but I think, wsdd is doing everything right here. So, you may open up a bug wherever the best place is for Dolphin.

**Comment by Mario156090** [comment]
Hello @christgau, I believe this is not a dolphin problem because I test this with another browser files and there is the same problem.

I tested too the hostname resolution and works perfectly.

**Comment by christgau** [comment]
>  I believe this is not a dolphin problem because I test this with another browser files and there is the same problem.

Then it could also be a problem of the other browsers (if you mean that).

You have stated yourself that "[you] watch the wsdd log and see the Windows 11 computer name and IP discovered.", so wsdd has done it's job as I pointed out. Everything that browsers do or don't do is not an issue of wsdd.

If you point out an issue between the interplay of browsers and wsdd, e.g. the API of wsdd is broken, then I am happy to look into that. At the moment, I don't have anything to look into as I am not a developer of Dolphin or other file browser and looking into those is currently out of my resources.

**Comment by Mario156090** [comment]
> > I believe this is not a dolphin problem because I test this with another browser files and there is the same problem.
> 
> Then it could also be a problem of the other browsers (if you mean that).
> 
> You have stated yourself that "[you] watch the wsdd log and see the Windows 11 computer name and IP discovered.", so wsdd has done it's job as I pointed out. Everything that browsers do or don't do is not an issue of wsdd.
> 
> If you point out an issue between the interplay of browsers and wsdd, e.g. the API of wsdd is broken, then I am happy to look into that. At the moment, I don't have anything to look into as I am not a developer of Dolphin or other file browser and looking into those is currently out of my resources.

I understand, OK, so I will to report in kde space.

Thankś for the support.
