### ISSUE TITLE
wsdd always marked as needing restart

### ISSUE THREAD

**Issue by rogerdc** [christgau/wsdd#197]
Reference: [wsdd always needs restart](https://github.com/liske/needrestart/issues/271)

wsdd is always marked as needing restart by `needrestart`. I'm opening this parallel issue because I don't know where the true issue lies. Here are the relevant lines that I can see from running `needrestart` verbosely: 

```
$ sudo needrestart -v -r l -m a
[main] eval /etc/needrestart/needrestart.conf
[main] needrestart v3.6
[...]
[Python] #3634: source=/usr/sbin/wsdd
[Core] #3634 uses obsolete script file(s):
[Core] #3634  /usr/sbin/wsdd
[main] #3634 is not a child
```

My full logs are available at the linked issue for the `needrestart` project.

**Comment by rogerdc** [comment]
Forgot to write down the version of wsdd: 

```
# apt show wsdd
Package: wsdd
Version: 2:0.7.0-2.1
Priority: optional
Section: net
Maintainer: Matthew Grant <matt@mattgrant.net.nz>
Installed-Size: 114 kB
Depends: python3 (>= 3.7)
Homepage: https://github.com/christgau/wsdd
Download-Size: 33.6 kB
APT-Manual-Installed: no
APT-Sources: http://deb.debian.org/debian sid/main amd64 Packages
Description: Python Web Services Discovery Daemon, Windows Net Browsing
[...]
```

**Comment by christgau** [comment]
> I don't know where the true issue lies. 

Sorry, but the provided information is not sufficient to work on anything. As soon as there is anything concrete and wsdd-related thing to be fixed, I'm happy to help but until then I'll close that issue. Please consider asking downstream/the distro-in-use as well.
