### ISSUE TITLE
ValueError: invalid resolve request: address does not match

### ISSUE THREAD

**Issue by jcl-concept** [christgau/wsdd#2]
hi,
I've successfully install the wsdd deamon on a Debian 9.6 with OpenMediaVault 4.1.15. I can now see my NAS from all my Windows 10 workstations. Great job !

I've a cyclic log in syslog :
> Dec 19 15:59:16 gayavault wsdd[22668]: 2018-12-19 15:59:16,630:wsdd INFO(pid 22668): handling WSD http://schemas.xmlsoap.org/ws/2005/04/discovery/Resolve type message (urn:uuid:361022dd-a158-424b-86e2-91d4c818865b)
> Dec 19 15:59:16 gayavault wsdd[22668]: 2018-12-19 15:59:16,631:wsdd ERROR(pid 22668): error in main loop
> Dec 19 15:59:16 gayavault wsdd[22668]: Traceback (most recent call last):
> Dec 19 15:59:16 gayavault wsdd[22668]:   File "/usr/bin/wsdd", line 680, in serve_wsd_requests
> Dec 19 15:59:16 gayavault wsdd[22668]:     key.data.handle_request()
> Dec 19 15:59:16 gayavault wsdd[22668]:   File "/usr/bin/wsdd", line 415, in handle_request
> Dec 19 15:59:16 gayavault wsdd[22668]:     msg = wsd_handle_message(msg, self.interface)
> Dec 19 15:59:16 gayavault wsdd[22668]:   File "/usr/bin/wsdd", line 396, in wsd_handle_message
> Dec 19 15:59:16 gayavault wsdd[22668]:     wsd_handle_resolve(resolve, interface.transport_address))
> Dec 19 15:59:16 gayavault wsdd[22668]:   File "/usr/bin/wsdd", line 295, in wsd_handle_resolve
> Dec 19 15:59:16 gayavault wsdd[22668]:     raise ValueError('invalid resolve request: address does not match')
> Dec 19 15:59:16 gayavault wsdd[22668]: ValueError: invalid resolve request: address does not match
> 

Can i help to understand and to manage this exception ?

Thank you.
Jean-Christophe

**Comment by christgau** [comment]
Hi Jean-Christophe and sorry for the delay

The error your are observing occurs when wsdd receives a Resolve request from a WSD client (which likely means Windows here) and the request does not contain the address (the UUID encoded as URN) of the endpoint that is executed by the wsdd instance. Refer to https://docs.microsoft.com/en-us/windows/desktop/wsdapi/resolve-message for details. That either means that the client has sent a malformed request with an invalid address or wsdd has a bug (which is not unrealistic, in general).

Can you reproduce the issue in a deterministic fashion or does happen only occasionally?

**Comment by jcl-concept** [comment]
Hi,

The issue are systematic and  can be reproduce (on my private network only ?) by asking a refresh of network neighborhood discovery from the Windows 10 Home 1809 file explorer app.

The network discovery is ok but the Linux syslog file (/var/log/syslog) is full of this exception from wsdd.
Maybe some WSDAPI settings needs to be set on my Windows workstations ...

If not, is it possible to have a more syslog friendly message from wsdd code ;-) ?

For testing purpose, i've adding a log trace line : 

```
...
def wsd_handle_resolve(resolve, xaddr):
    addr = resolve.find('./wsa:EndpointReference/wsa:Address', namespaces)
    if addr is None:
        raise ValueError('invalid resolve request: missing endpoint address')

    ## JCL Trace of uuid
    logger.info('handle Resolve addr.text {0} args.uuid.urn ({1})'.format(addr.text, args.uuid.urn))

    if not addr.text == args.uuid.urn:
        raise ValueError('invalid resolve request: address does not match')
....
```
and the two URN are very rarely identical in fact.... It seems thats only true at very first connection of the client on the network (boot of the client for exemple).

Ask me if want some other tests.

Jean-Christophe

**Comment by christgau** [comment]
Thanks for your feedback. 

> The issue are systematic and can be reproduce (on my private network only ?) by asking a refresh of network neighborhood discovery from the Windows 10 Home 1809 file explorer app.

Hmmm, strange. I am not able to reproduce the issue with a Windows 10 Pro 1809 client. Discovery works fine without warnings or errors. 

> If not, is it possible to have a more syslog friendly message from wsdd code ;-) ?

Nevertheless, I agree that shouting out an error along with a stack trace caused by a (potentially) wrong request which is actually handled by wsdd should not flood the (sys)log. I think, raising an exception in lines 295, 292, 275, and 278 is not appropriate. Those might be changed to debug messages or warnings (line 275). Thus, the log will be clean by default, even if a client misbehaves. 

> and the two URN are very rarely identical in fact

Well, that's strange. Could you please set the log level to debug (`-vv`), reproduce the issue, and post the log output? Please also keep your logging of the UUID.

**Comment by jcl-concept** [comment]
Hi Steffen,
here is some log files without and with (after 20:30 ...) the -vv and UUID log.

wsdd.log :
[https://pastebin.com/tVXZD78x](https://pastebin.com/tVXZD78x)

wsdd.addr.text.log :
[https://pastebin.com/vJAJ7gYV](https://pastebin.com/vJAJ7gYV)

I've several equipment on the network like NAS with samba, Raspberries, Printer, Android and iOS Phones and some Windows computers (Windows 10, Seven …).

As you will see, there is a lot of Resolve exception :-(...
In the wsdd.addr.text.log, there is 1 log without the urn prefix….. strange….

**Comment by christgau** [comment]
Thank you for the log files. I'll dig into them as soon as I can...
