### ISSUE TITLE
Question about wsdd scan

### ISSUE THREAD

**Issue by tecbeat** [christgau/wsdd#200]
My problem: 
I am relatively new to wsdd and my printer is an Epson ET-3850 and I am trying to scan from it to a Debian/Ubuntu LXC. Finding my printer via wsdd works, but I have not been able to get the printer to detect the LXC as a service/end device. Is this even possible (are there other options) or have I missed something? Scan to SMB does not work or is not supported and connecting a Rasberry Pi is the last option. Thanks in advance for your help.

**Comment by christgau** [comment]
> Is this even possible [...]?

Frankly speaking: Please check the capabilities of your printer.

Not so frankly speaking: Wsdd is for discovering devices/services in the network. One of the services can be file sharing. If your printer supports the WSD protocol you can make your Linux machine offering that service discoverable to the printer. But using the file sharing service is a task of the printer. If it does not support Samba/Windows File Sharing, wsdd cannot to anything about this...

> Scan to SMB does not work or is not supported

... you see.
