### ISSUE TITLE
Is it possible to set a display name?

### ISSUE THREAD

**Issue by kroese** [christgau/wsdd#204]
I have an issue where the container running wsdd cannot reached by DNS from the Windows machine, only by IP address.

So to solve this, I used the `-n` parameter of wsdd to set the hostname to the IP address.

This works, but ofcourse in Windows will now show the machine by its IP address in the Network Neighbourhood.

Is it possible to make this machine appear with a nice display name? I dont know if the Network Discovery protocol has any functionality for that, to separate the machine name from the machine address? But if so, it would be really nice if wsdd added support for that.

**Comment by christgau** [comment]
> Can you make a machine appear with a different hostname in the Network Neighbourhood than the hostname that will be used to connect?

AFAIK, no.

**Comment by christgau** [comment]
Within the WSD protocol (or the wsdd implementation of it), the `wsdp:FriendlyName` property is used to tell the searching maschine the (guess what) user friendly name of the discovered device. AFAIK, this friendly name is then used by Windows to perform a name resolution. So you cannot just put a custom string there, without breaking things. To my understanding of the [WS-Transfer specification](https://schemas.xmlsoap.org/ws/2006/02/devprof/devicesprofile.xsd), which describes what can be exchanged w.r.t. to meta data, there is no equivalent to the `server string` configuration variable from samba, which "sets what will appear in browse lists next to the machine name". 

Sorry to say, but I don't see a way for what you attempt to achieve. If somebody knows of a way, feel free to open a PR.
