### ISSUE TITLE
Ubuntu 24.04 server apt install does not write wsdd.service  or etc/default/wsdd files

### ISSUE THREAD

**Issue by XXtreem11** [christgau/wsdd#212]
Brand new install of Ubuntu 24.04 server 
Linux asgard 6.8.0-38-generic #38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Distributor ID: Ubuntu
Description:    Ubuntu 24.04 LTS
Release:        24.04
Codename:       noble

installed via 'apt instal wsdd'

tried to start the service and there was no wsdd.service file in the /etc/systemd/system directory
created the file from the git source... then the service would not start
Jul 25 11:00:36 asgard systemd[1]: wsdd.service: Failed to load environment files: No such file or directory
Jul 25 11:00:36 asgard systemd[1]: wsdd.service: Failed to spawn 'start' task: No such file or directory
Jul 25 11:00:36 asgard systemd[1]: wsdd.service: Failed with result 'resources'.
Jul 25 11:00:36 asgard systemd[1]: Failed to start wsdd.service - Web Services Dynamic Discovery host daemon.

did 'sudo touch /etc/default/wsdd'

then the service started.

**Comment by ondrejholy** [comment]
It would be good to change the https://github.com/christgau/wsdd/blob/v0.8/etc/systemd/wsdd.service#L15 line to `EnvironmentFile=-/etc/default/wsdd`. This is one of the changes we do in Fedora...

**Comment by christgau** [comment]
> It would be good to change the https://github.com/christgau/wsdd/blob/v0.8/etc/systemd/wsdd.service#L15 line to `EnvironmentFile=-/etc/default/wsdd`.

I can change accordingly, but seems also like a packaging error for Ubuntu.

**Comment by morbius1gh** [comment]
There are two wsdd packages thanks to Debian in Ubuntu 24.04:

**wsdd** which is called by a new gvfsd-wsdd backend that enables the file manager in Ubuntu to discover Windows SMB hosts. It does not create s service.

**wsdd-server** which enables samba host discovery by Windows clients. This does create a service.

Installing wsdd-server also installs wsdd.

This solves the issue where the Linux machine could not both discover and be discovered at the same time. Now they are two different processes.

**Comment by XXtreem11** [comment]
So does all the references in docs and internet posts need to specify wsdd-server rather than just wsdd?  What's the use case to separate the 2 into separate packages?

**Comment by morbius1gh** [comment]
> So does all the references in docs and internet posts need to specify wsdd-server rather than just wsdd? What's the use case to separate the 2 into separate packages?

Here is the original Debian bug report that initiated the split of wsdd and the creation of the server specific wsdd package: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1064060

In addition I would note that if the old wsdd was running as a server you ( gvfs or kde ) could not initiate another wsdd to find other hosts. This split allows both server and client processes to run independently.

**Comment by drmod3** [comment]
Thanks for all the input.

I too updated to Kubuntu 24.04 flavor of Ubuntu/Linux. We have 3-Kubuntu 24.04 computers and 3-Windows 10 computers on the network. Originally, when wsdd was installed, the service was not installed. 

With wsdd only, my Kubuntu machines can see the  Windows and other Kubuntu computers on the network. But Windows sees none of the Kubuntu computers.

After reading this discussion, I removed wsdd  from one computer with "sudo apt-get -y autoremove --purge wsdd.  Then installed sudo apt install wsdd-server. 

With wsdd-server, that machine sees only itself on the network, but no other Kubuntu or Windows. Windows can now see that machine but not the ones with only wsdd.

It seems so close. Did I miss something? Do I need to start or modify a file?

I appreciate your efforts and help.

**Comment by morbius1gh** [comment]
Respectfully, I think your question is best asked in the Ubuntu forums or as a Kubuntu bug report.

WSDD has nothing to do with Linux to Linux or Linux to MacOS discovery since that is handled by Samba itself using avahi.

Installing wsdd by itself will do nothing in KDE since it has it's own implementation: kdsoap-ws-discovery-client. KDE can see Win10 but not the other way around.

Installing wsdd-server on KDE breaks kdsoap-ws-discovery-client. Now you have the reverse problem: Win10 can see Kubuntu but not the other way around.

Gnome, XFCE, Cinnamon, etc..  resolved this issue with a new gvfsd-wsdd backend. KDE has not.

**Comment by drmod3** [comment]
Thanks for your information

**Comment by christgau** [comment]
Given 006a799, I think, this issue can be closed.
