### ISSUE TITLE
Debian Jessie and /run/wsdd

### ISSUE THREAD

**Issue by NotTimTam** [christgau/wsdd#213]
I am running an old version of Debian Jessie on old hardware that cannot be updated. As such I have been going through and manually installing wsdd to work on my samba server on it.

I followed the instructions in [this thread](https://askubuntu.com/questions/1427184/file-sharing-fiasco-dancing-the-samba-mambo) and:
- Downloaded the `master.zip` file.
- Extracted the files and copied them to the right directories.
- Then enabled and started the services.

When I check if the services have started, I get this error:

```
chip@chip:~/downloads$ sudo systemctl daemon-reload; sudo systemctl start wsdd; sudo systemctl enable wsdd
chip@chip:~/downloads$ systemctl status wsdd.service
* wsdd.service - Web Services Dynamic Discovery host daemon
   Loaded: loaded (/etc/systemd/system/wsdd.service; enabled)
   Active: failed (Result: exit-code) since Fri 2024-08-09 19:57:10 MST; 4s ago
     Docs: man:wsdd(8)
 Main PID: 2260 (code=exited, status=2)
```

I ran the start script manually to see the error, and this is what I get:
```
chip@chip:~/downloads$ /usr/bin/wsdd --shortlog --chroot=/run/wsdd $WSDD_PARAMS
WARNING: no interface given, using all interfaces
ERROR: could not chroot to /run/wsdd: [Errno 2] No such file or directory: '/run/wsdd'
```

What is supposed to be in `/run/wsdd`?

Thanks.

**Comment by christgau** [comment]
> I ran the start script manually to see the error, and this is what I get:

The actual error might be different. Use `journalctl` to check what the wsdd unit experiences as an error.

> What is supposed to be in `/run/wsdd`?

Nothing. It should be an empty directory.
