### ISSUE TITLE
Checking .startswith('lo') may miss some interfaces

### ISSUE THREAD

**Issue by chemoelectric** [christgau/wsdd#22]
I give my interfaces names based on position in the computer, and so my main interface is ‘lower0’.

Unfortunately this interface would be excluded by .startswith('lo'), even if the interface were specified with the -i option.

**Comment by christgau** [comment]
The latest commit now performs the check for a loopback interface based on flags provided by the OS. The named-based check is gone. Thus, it should now work on your box.

**Comment by chemoelectric** [comment]
Sorry for me taking so long to thank you. I am a little on the slow side and had been running it with my own patch for a while.

I adapted your ebuild for my own overlay at https://bitbucket.org/chemoelectric/chemoelectric-overlay/ (long since kicked off of layman for my failures to respond quickly :) ), bumped version to 0.5, and added acct-user/wsdd and acct-group/wsdd so repoman would not complain about deprecated user.eclass. :)

**Comment by christgau** [comment]
>Sorry for me taking so long to thank you. I am a little on the slow side and had been running it with my own patch for a while.

Feedback is welcome at any time 😉

There will be a new release in the near future and things have changed again. On Linux all addresses within127.0.0.0/8, which is reserved for loopback (RFC 5735), are ignored. On FreeBSD the check is still based on flags.

> added acct-user/wsdd and acct-group/wsdd so repoman would not complain about deprecated user.eclass.

Good point, Apparently, I need to update my ebuilds. 😉 And, btw, I pushed the package in the Guru repository as well.
