### ISSUE TITLE
Resolution takes several seconds

### ISSUE THREAD

**Issue by Shohreh** [christgau/wsdd#220]
Hello,

On a Windows 10 host and a Debian appliance connected on the same  switch, it takes several seconds to see the list of shared ressources after typing "net view \\\\debian".

Is it to be expected, or is it due to wrong options when launching wsdd?

Also, how should I configure wsdd so that its settings are used by systemd (eg. --interface eth0 --ipv4only)?

FWIW, I'm running  Samba 4.17.12-Debian and wsdd v0.7.0.

Thank you.

=============== netstat -tunlp
```
tcp        0      0 192.168.0.15:5357 0.0.0.0:*               
LISTEN      6192/python3
tcp6       0      0 fe80::50:43ff:fee7:5357 :::*                    
LISTEN      6192/python3
udp        0      0 192.168.0.15:3702 
0.0.0.0:*                           6192/python3
udp        0      0 239.255.255.250:3702 
0.0.0.0:*                           6192/python3
udp        0      0 0.0.0.0:39450 0.0.0.0:*                           
6192/python3
```

=============== systemctl status wsdd
```
…
Oct 17 11:42:24 debian wsdd[6192]: WARNING: no interface given, using all interfaces
```

--
Edit:
```
systemctl stop wsdd
wsdd --verbose --ipv4only --interface eth0
```

Nothing displayed when running "c:\>net view \\debian" on Windows. Issue located in Windows?

On Windows, running services.msc shows no mention of "Web Services Discovery". Is it "WinHTTP Web Proxy Auto-Discovery Service", which is running?

Both "Function Discovery Provider Host” and “Function Discovery Resource Publication” services are running, with "Startup Type" set to "Manual" and "Manual (Trigger Start)" respectively.

Still nothing displayed with "wsdd -vvv -w WORKGROUP --ipv4only --interface eth0" and "c:\>net view \\debian". It looks like Windows doesn't use WSD and relies on broadcasting.

**Comment by Shohreh** [comment]
Turns out it's something to do with Debian 12 itlsef, not wsdd.

**Comment by christgau** [comment]
>>  it takes several seconds to see the list of shared ressources after typing "net view \\debian".
> Turns out it's something to do with Debian 12 itself (authentication ? authorization?), not wsdd.

Yes. If you want to know what on the "debian" host, than you have already _discovered_ that the machine offers a Samba share. The _d_ in _WSD_ stands for discovery. Everything beyond discovery is out of wsdd's scope.
