### ISSUE TITLE
How to install in systemd manually? What is webfsd?

### ISSUE THREAD

**Issue by Shohreh** [christgau/wsdd#221]
Hello,

Two other newbie questions:

1. Since wsdd is only available from Debian 12, what's the procedure to install wsdd in systemd manually?
zip file:
```
/etc/sytemd/
wsdd.defaults
wsdd.service
```

Before that, should I edit the two files above to launch wsdd? Temporarily, I used the following:
`/usr/bin/wsdd.py --verbose --ipv4only --interface eth0 &`

2. What is webfsd listening on tcp6? Is it part of wsdd?

Thank you.

**Comment by christgau** [comment]
> Two other newbie questions:

So, they aren't issues. 

Please consider a) opening a discussion for those things and b) invest _your_ time into some research regarding those questions. 

Nevertheless...

> Since wsdd is only available from Debian 12

Not really. Check https://github.com/christgau/wsdd/blob/v0.7.1/README.md or #19. Looks like the packages are still available. 

>  what's the procedure to install wsdd in systemd manually?

That's a systemd question. Please make yourself familiar to systemd. There are no real wsdd specifics here. All pieces, i.e. the two files you mentioned, are lying on the table to be picked up.

> Is [webfsd] part of wsdd?

No.
