### ISSUE TITLE
WSDD doesn't use /etc/conf.d/wsdd

### ISSUE THREAD

**Issue by Mario156090** [christgau/wsdd#222]
Hello dear WSDD Owner, I am checking a bug with WSDD service. If I config a PARAMS content on /etc/conf.d/wsdd file and start the service, the service never read that information. I am using Arch Linux. On the service I can see a message:

`dic 05 18:11:49 asus-arch (wsdd)[1269]: wsdd.service: Referenced but unset environment variable evaluates to an empty string: WSDD_PARAMS
`

So I don't know if this is a WSDD problem or a Arch Linux problem. This is my full service state output:

`    ~  systemctl status wsdd.service                                                        ✔  06:24:34 PM  
● wsdd.service - Web Services Dynamic Discovery host daemon
     Loaded: loaded (/usr/lib/systemd/system/wsdd.service; enabled; preset: disabled)
     Active: active (running) since Thu 2024-12-05 18:11:49 -05; 14min ago
 Invocation: 6f320bed8c0946e4a7d41b6ed418acd7
       Docs: man:wsdd(8)
   Main PID: 1269 (python3)
      Tasks: 1 (limit: 45391)
     Memory: 21.8M (peak: 23.9M)
        CPU: 185ms
     CGroup: /system.slice/wsdd.service
             └─1269 python3 /usr/bin/wsdd --shortlog --chroot=/run/wsdd

dic 05 18:11:49 asus-arch systemd[1]: Started Web Services Dynamic Discovery host daemon.
dic 05 18:11:49 asus-arch (wsdd)[1269]: wsdd.service: Referenced but unset environment variable evaluates to an empty string: WSDD_PARAMS
dic 05 18:11:49 asus-arch wsdd[1269]: WARNING: no interface given, using all interfaces
`

**Comment by christgau** [comment]
>  I am checking a bug with WSDD service. If I config a PARAMS content on /etc/conf.d/wsdd file and start the service, the service never read that information. I am using Arch Linux.

From my point of view, it looks like a packing error for Arch. There's a patch, that [renames the variable inside the conf file](https://gitlab.archlinux.org/archlinux/packaging/packages/wsdd/-/blob/main/0001-Modify-systemd-service-for-Arch.patch?ref_type=heads#L24-25) to `PARAMS` but the [unit file still refers](https://gitlab.archlinux.org/archlinux/packaging/packages/wsdd/-/blob/main/0001-Modify-systemd-service-for-Arch.patch?ref_type=heads#L46) to `WSDD_PARAMS`. 

Please check with downstream for this inconsistency. Feel free to re-open this issue in case it requires fixes here.
