### ISSUE TITLE
Handle changes of interfaces

### ISSUE THREAD

**Issue by christgau** [christgau/wsdd#25]
wsdd is currently not able to handle changes of interfaces, like new IP addresses as a result of a new DHCP lease or switched networks, addresses become non-tentative (see #18), or the addition or removal of interfaces. Those events can be handled with netlink(7) sockets under Linux, or route(4) sockets under FreeBSD.

This would also prevent DAD race conditions during system boot as observed by users in #18.

**Comment by christgau** [comment]
For FreeBSD, the developers over there have been informed about the issue with the not-so-helpful route socket messages containing tentative addresses. The will have a look at it, but things may take time.

**Comment by Nodens-** [comment]
Since this currently works for Linux and maintains current functionality for FreeBSD, could it be merged to master so that it will land on Fedora sometime soon and save me the hassle of manually deploying feat/discovery branch on our boxes and later reverting back to package manager? :)

**Comment by christgau** [comment]
I'll try to bring the changes in the feature branch into master as soon as I can and create a release after that. Some users appear to still have problems (#40) or at least did not report that the feature branch solves the problem, although it does IMO (#18). But it is unclear whether the latest commits have been used or not. I suspect the latter is the case.

**Comment by Nodens-** [comment]
@christgau Thank you very much. I suspect as much myself as it works in my tests.
