### ISSUE TITLE
Fedora / Firewalld problem

### ISSUE THREAD

**Issue by denniskarlsson** [christgau/wsdd#27]
I have a few Fedora 31 servers running wsdd. On some of them wsdd does not respond.
I know it has something to do with Firewalld (iptables).
As soon as I disable Firewalld it works.

**Does anyone know how to allow wsdd through Firewalld?**

### NOT RESPONDING
```
/usr/local/bin/wsdd.py -4 --shortlog --preserve-case --workgroup dknet --hostname ns1 -v

INFO: 192.168.0.50:58982(ens1) - - "Probe urn:uuid:cab75101-5b0e-4b28-97b7-42f42efbb2c9 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:ccf2cdc9-7295-4f39-b984-2ecec1a87305 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:88f5a768-48e8-42b5-9434-c5f292a23614 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:2bf15957-7b39-4698-a26c-562da93833d5 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:23dafe0c-dca6-412d-81f9-2f874a95266a UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:704a3dd7-6fd9-4ad6-9574-f828ff53e9d3 UDP" - -
```

### RESPONDING
```
/usr/local/bin/wsdd.py -4 --shortlog --preserve-case --workgroup dknet --hostname mail -v

INFO: 192.168.0.50:58982(ens1) - - "Probe urn:uuid:cab75101-5b0e-4b28-97b7-42f42efbb2c9 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:ccf2cdc9-7295-4f39-b984-2ecec1a87305 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:88f5a768-48e8-42b5-9434-c5f292a23614 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:2bf15957-7b39-4698-a26c-562da93833d5 UDP" - -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:23dafe0c-dca6-412d-81f9-2f874a95266a UDP" - -
INFO: 192.168.0.50 - - "POST /6a990cbc-8f22-5778-a996-875aabffbb47 HTTP/1.1" 200 -
INFO: 192.168.0.50:58984(ens1) - - "Resolve urn:uuid:704a3dd7-6fd9-4ad6-9574-f828ff53e9d3 UDP" - -
```

I added this file to Firewalld and enabled it but still no luck.
```
[root@machine:~]# cat /usr/lib/firewalld/services/wsdd.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>WS-Discovery</short>
  <description>WS-Discovery is a network protocol based on the Internet protocol suite for advertisement and discovery of network services and presence information.</description>
  <port protocol="udp" port="3702"/>
  <destination ipv4="239.255.255.250" ipv6="FF02::C"/>
</service>
[root@machine:~]#
```

```
[root@machine:~]# firewall-cmd --list-all
public
  target: default
  icmp-block-inversion: no
  interfaces:
  sources:
  services: dhcpv6-client dns mdns mountd nfs nrpe rpc-bind samba snmp ssh wsdd
  ports:
  protocols:
  masquerade: no
  forward-ports:
  source-ports:
  icmp-blocks:
  rich rules:

[root@machine:~]#
```

**Comment by christgau** [comment]
Just have a look at the readme or the man page 😉

> Incoming TCP traffic (and related outgoing traffic) on port 5357 must be allowed.

That one is missing in your config (for both IPv6 and IPv4, dont know if this matters for firewalld). 

Please also note that there is a known problem when wsdd should start at boot which is related to automatic IPv6 address configuration but this would show up with an error message like "OS Error 99" in the log (see #18 for details).

**Comment by denniskarlsson** [comment]
Thank you. It worked right away. =)

Sorry for not reading the instructions correctly.
Have a nice day, sir.

**Comment by christgau** [comment]
No problem, you're welcome.

**Comment by denniskarlsson** [comment]
Sure. Here is the file I ended up with.

[root@machine:~]# cat /usr/lib/firewalld/services/wsdd.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
        <short>WS-Discovery</short>
        <description>Web Services Dynamic Discovery (WS-Discovery) is a technical specification that defines a multicast discovery protocol to locate services on a local network.</description>
        <port protocol="udp" port="3702"/>
        <destination ipv4="239.255.255.250" ipv6="FF02::C"/>
        <port protocol="tcp" port="5357"/>
        <include service="wsd"/>
</service>
[root@machine:~]#

**Comment by christgau** [comment]
For Fedora, official packages of wsdd are available. Thus, you may consider installing those from the repo instead of a manual installation. Alternatively, you can peek into the package sources to have a look what their firewalld config file is doing for wsdd.

**Comment by denniskarlsson** [comment]
Do you know what the package name in Fedora is? I can't find it.

**Comment by christgau** [comment]
According to https://pkgs.org/search/?q=wsdd, you should simply find and install it as wsdd. I was able to search (and find) it on CentOS 7 within EPEL repo that way.

**Comment by denniskarlsson** [comment]
This is the result with core and updates repos on Fedora 31.
`[root@machine:~]# dnf search wsdd
No matches found.
[root@machine:~]#`

**Comment by christgau** [comment]
Mh, true. Fedora's online package search does not list it. On the other hand it appears to be there: https://src.fedoraproject.org/rpms/wsdd. 

Anyways, the TCP port 3702 is not required to be open - at least in the vanilla sources. Haven't checked if the packages apply any patches.

**Comment by TopGeartm** [comment]
Thankyou.
I tried your files and they are the same as what I had done myself and those do not work for me either.

I have setup wsdd as a service

WWDD Service

[Unit]
Description=Web Services Dynamic Discovery Host Daemon
After=network.target network-online.target multi-user.target
Wants=network-online.target
Wants=samba-ad-dc.service

[Service]
Type=simple
ExecStart=/usr/bin/wsdd -i enp5s0 -4 --shortlog
User=wsdd
Group=wsdd

[Install]
WantedBy=multi-user.target

This is running fine. I did have the bug with ipv6 so I have set this to run as ipv4. 
I am using samba v4.12 set as an active directory domain controller. Turning the firewall off everything works. Running Cent 8

I setup my firewall service below:

<?xml version="1.0" encoding="utf-8"?>
<service>
        <short>wwsd</short>
        <description>wwsd</description>
        <port protocol="udp" port="3702"/>
	<port protocol="udp" port="5355"/>
	<port protocol="tcp" port="4"/>
        <port protocol="tcp" port="5357"/>
</service>

firewall-cmd --zone=public --add-service=wsdd --permanent
firewall-cmd --reload
It does not work

After some trial and error manually opening port ranges I have got it to work using the command below:

firewall-cmd --zone=public --add-port=5357/udp --add-port=3702/udp --add-port=5357/tcp --add-port=5355/udp

If I don't enable port 5355 I cannot ping the server from windows.
It is odd that the service does not seem to be opening the ports

**Comment by TopGeartm** [comment]
Finally got it working:

wsdd.xml

```
cat << EOF > /usr/lib/firewalld/services/wsdd.xml
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>Web Services Dynamic Discovery Host Daemon</short>
  <description>wsdd implements a Web Service Discovery host daemon. This enables (Samba) hosts, like your local NAS de
vice, to be found by Web Service Discovery Clients like Windows.</description>
  <port protocol="udp" port="3702"/>
  <port protocol="tcp" port="5357-5358"/>
  <port protocol="udp" port="5355"/>
  <port protocol="tcp" port="445"/>
</service>
EOF
```

These were the ports I needed to open

udp port="3702 # needed for network manager
tcp port="5357"/> # needed for network manager (http)
tcp port="5358"/> # needed for network manager (https) *optional*
udp" port="5355"/> # needed for windows 10 ping
tcp" port="445"/>  # needed to access windows share

The other issue I was having was that firewalld files stored in /etc/firewalld/services override files stored in /usr/lib/firewalld/services/ so when I was updating the service file it was doing nothing. As soon as I deleted the file /etc/firewalld/services/wsdd.xml and then figured out the ports it worked great. I must have made this file trying to get it to work previously.

I hope this saves someone a headache

**Comment by christgau** [comment]
Just for the records:

> udp port="3702 # needed for network manager
> tcp port="5357" # needed for network manager (http)

Those are the only ones technically needed by wsdd. The firewall configuration for wsdd (and nothing more) should only include these two ports. Anything more might lead to security issues.

> tcp port="5358" # needed for network manager (https) optional

There is no HTTPS implementation in wsdd, but that port would be used in case. That port specification can be omitted. It is of no use.

> udp" port="5355 # needed for windows 10 ping

This the port for LLMNR, a service that is not implemented by wsdd but by other services, e.g. systemd-resolved. It is used by Windows aside other name lookup methods including the regular DNS protocol to resolve the name shown in Explorer's Network view and to finally connect with that machine. A name resolution - regardless of the actual method - is required to get "everything" (i.e., see computer in Explorer and _connect_ to it) work as expected. 

> tcp" port="445" # needed to access windows share

This is the Samba port and as such not serviced by wsdd.
