### ISSUE TITLE
Interfaces with multiple IP addresses 

### ISSUE THREAD

**Issue by spacemonkey211** [christgau/wsdd#31]
There is no way to specify which IP address to use on interfaces with multiple IP addresses.  Ubuntu uses Netplan for network config.  Unfortunately, there is no way to implement subinterfaces like before and so all extra IP addresses use the same interface.  It would be nice to just specify the IP address and not the interface alone.

**Comment by christgau** [comment]
Good proposal. Currently all IPs of the desired address family/ies are used. For IPv6 all link-locals. 

So, do you want to do something like this: `wsdd -i 192.168.1.23 -i fe80::1234 -i eth2` ?

**Comment by spacemonkey211** [comment]
That would work.  I did a quick and dirty patch using capital i just to see if it would work but as a restrictor.  So the interface and IP needed to match (if both arguments are present) for arg.interface to be valid.   That worked and I was getting discovery from the IP and port selected, however, I did run into a snag.  I decided to run samba on eth2 only and had wsdd as eth2 as well.  Windows 10 discovers it fine but cannot connect.  Looking at the Windows logs, Windows 10 is trying to connect to samba using eth1's IP address (192.168.1.60), but communicating to eth2 (192.168.1.65) for discovery.

**Comment by christgau** [comment]
@spacemonkey211 I just added the requested feature with the commit mentioned above. Could you give it a try? I've tested it on my local machine and it worked, but I'm interested in whether it works in your network setup or not.

**Comment by spacemonkey211** [comment]
It does not seem to work for me.  Using only an IP address, it doesn't bind to anything.  It only tries the loopback.  Do I need to pass it an interface and IP?

**Comment by christgau** [comment]
Please make sure you use the code from the feat/discovery branch and not the master. The following works for me:

```sh
$ wget https://raw.githubusercontent.com/christgau/wsdd/979cb4f152a6bd2a0a8f75c24a36d12b422ce2ea/src/wsdd.py
$ ip -4 addr | fgrep inet | fgrep -v '127.0.0.1' # choose an address from the result
$ python3 wsdd.py -s -i $chosen_addr
...
WARNING: new address $chosen_addr on $interface # NOT directly followed by an "ignoring address" line
...
^Z
$ ss -tlnp | fgrep python
# you should see an LISTEN entry with the chosen address and port 5357 here
```

Loop-back addresses should never be used by wsdd. They are ignored

**Comment by spacemonkey211** [comment]
Yes, your suggestion is what I did in the beginning.  

I made sure again to download the correct branch.  When I run it, there is no output from ss or netstat.  I checked and wsdd is running, it just doesn't bind to any address.   

I am successfully running an old version of wsdd that I patched, but looking at the new code, a lot of refactoring has happened in the past couple of months.  My patch would no longer work at all, and I would need to take a look at the code again.  I'm not a developer but only dabble in it on the side.

**Comment by christgau** [comment]
> When I run it, there is no output from ss or netstat. 

Then, wsdd is not listening to any address at all. That's definitely not what you wanted and not the purpose of the program. 😉

Could you provide the command lines you use to create the additional IP address for the interface and to start wsdd? The output of `ip addr` (of `ifconfig`) would be helpful as well.

**Comment by spacemonkey211** [comment]
`spacemonkey@server:~$ ip -4 addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: eno1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.1.60/24 brd 192.168.1.255 scope global eno1
       valid_lft forever preferred_lft forever
    inet 192.168.1.61/24 brd 192.168.1.255 scope global secondary eno1
       valid_lft forever preferred_lft forever
    inet 192.168.1.62/24 brd 192.168.1.255 scope global secondary eno1
       valid_lft forever preferred_lft forever
    inet 192.168.1.63/24 brd 192.168.1.255 scope global secondary eno1
       valid_lft forever preferred_lft forever
    inet 192.168.1.64/24 brd 192.168.1.255 scope global secondary eno1
       valid_lft forever preferred_lft forever
3: eno2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.1.50/24 brd 192.168.1.255 scope global eno2
       valid_lft forever preferred_lft forever`

`spacemonkey@server:~$ cat /etc/netplan/01-netconf.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    eno1:
      dhcp4: false
      addresses:
        - 192.168.1.60/24
        - 192.168.1.61/24
        - 192.168.1.62/24
        - 192.168.1.63/24
        - 192.168.1.64/24
      gateway4: 192.168.1.1
      dhcp6: false
    eno2:
      dhcp4: true
      dhcp6: false`

`spacemonkey@server:~$ python3 /usr/local/bin/wsdd1 --shortlog -P 192.168.1.64 -4 &
[1] 2285324
spacemonkey@server:~$ sudo ss -nptl | grep python
LISTEN    0         5             192.168.1.64:5357             0.0.0.0:*        users:(("python3",pid=2285324,fd=6))
`
That is the output of my patched old version of wsdd.  I added the -P switch for IP addresses.  Next is the newest version from the ip address enhancement branch.

`spacemonkey@server:~/wsdd$ python3 wsdd.py -i 192.168.1.64 -4 &
[1] 2296978
spacemonkey@server:~/wsdd$ wsdd.py:989: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('new address {} on {}'.format(addr, interface.name))
2020-05-26 21:34:03,479:wsdd WARNING(pid 2296978): new address 127.0.0.1 on lo
wsdd.py:992: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  logger.warn('ignoring address on {}'.format(interface.name))
2020-05-26 21:34:03,479:wsdd WARNING(pid 2296978): ignoring address on lo
spacemonkey@server:~/wsdd$ sudo ss -nptl | grep python
spacemonkey@server:~/wsdd$`

**Comment by christgau** [comment]
Thanks for your detailed feedback. Based on it I tried to reproduce the issue. FWIW, an IP address with "secondary" flag can be achieved by adding a new address to an interface in the same subnet of an existing address.

However, I was not able to reproduce the problem:

```
$ ip address add 192.168.2.120/24 dev wlp3s0
$ ip -4 addr
...
3: wlp3s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    inet 192.168.2.62/24 brd 192.168.2.255 scope global dynamic noprefixroute wlp3s0
       valid_lft 844814sec preferred_lft 844814sec
    inet 192.168.2.120/24 brd 192.168.2.255 scope global secondary wlp3s0
       valid_lft forever preferred_lft forever
...
$ ./wsdd.py -s -v -i 192.168.2.120 -4
INFO: using pre-defined UUID 3c95265c-5f6b-5496-ac73-a9354ba76e93
INFO: new address 127.0.0.1 on lo
INFO: ignoring that address on lo
INFO: new address 192.168.2.62 on wlp3s0
INFO: ignoring that address on wlp3s0
INFO: new address 192.168.2.120 on wlp3s0
INFO: joined multicast group ('239.255.255.250', 3702) on 192.168.2.120%wlp3s0
INFO: new address ::1 on lo
INFO: ignoring that address on lo
INFO: new address 2003:ca:ef39:ee00:224:d7ff:fe0c:e470 on wlp3s0
INFO: ignoring that address on wlp3s0
INFO: new address fe80::224:d7ff:fe0c:e470 on wlp3s0
INFO: ignoring that address on wlp3s0
INFO: 192.168.2.100 - - "POST /3c95265c-5f6b-5496-ac73-a9354ba76e93 HTTP/1.1" 200 -
^Z
$ ss -nptl | grep python
LISTEN    0      0      192.168.2.120:5357     0.0.0.0:*    ... (("python3",...
```

(Note that all messages have info priority, but that's the only difference to the latest commit in feat/develop)

> I am using several docker containers and binding then all to separate IP's. 

But wsdd is not running in a container but directly on the host, I assume. Running inside a container may cause problems.
