### ISSUE TITLE
Windows shows host only after first wsdd start.

### ISSUE THREAD

**Issue by black-ish** [christgau/wsdd#32]
Hello,
I have been trying to get this to work now on three systems (1VM, 1 RPi and 1 NAS (All on Alpine Linux)) and all have the same behaviour, Windows clients only see the host once after the service starts.
Every client/host is configured with a static IP and running on IPv4 only mode.

As soon as any client tries a network refresh (as in either pressing F5 or the refresh button in the explorer) the host disappears from the list and never shows up again, also not after a reboot of the client, until the service is restarted on the host.

The wsdd daemon runs with the following flags: "-4 -i eth1"
The log also only shows the POST only once and then never shows anything after that until restart of the daemon.

Is there anything I missed in setting it up? Am I the only one having that problem?
I read the other issues that might be related to this but that I could have tried I tried.

Alpine Linux uses OpenRC so no systemd. And I allow everything through iptables that needs it and it "works" but basically only once and after that it's going back to entering either the hostname or the IP address.

**Comment by christgau** [comment]
This might be related to #8. Is the interface you bind to (`eth1`) affected by NAT or do you have multiple IPv4 addresses bind to that single interface?

The effect on startup of wsdd is a multicast `Hello` message that contains the address to which the POST should be made. This apparently succeeds since you can see the host after that. However, during a refresh, unicast messages are exchanged and it appears that Windows checks whether the unicast sender address (used by wsdd) and the address in the message body match. If that is not the case, windows does not do the POST and the host is not detected.

You may use wireshark/tcpdump to check the packages and addresses in use to detect the failure.

**Comment by black-ish** [comment]
No all interfaces are direct connections, no NAT no multiple IP addresses nothing.
I never check much into unicast and so on, does that go over the same address UDP 239.255.255.250:3702? Or is that what's port 5357 is for? Wait, is it that I also need to allow TCP on the 239.255.255.250:3702?

**Comment by christgau** [comment]
> I never check much into unicast and so on, does that go over the same address UDP 239.255.255.250:3702?

Unicast traffic does not to go to multicast addresses, but to the address of the client ports. You can find an overview of the message flow here: https://docs.microsoft.com/en-us/windows/win32/wsdapi/discovery-and-metadata-exchange-message-patterns

> Wait, is it that I also need to allow TCP on the 239.255.255.250:3702

For the firewall settings, please refer to https://github.com/christgau/wsdd#firewall-setup.

**Comment by black-ish** [comment]
Yes I checked those and it's UDP 239.255.255.250:3702 and TCP on all addresses on port 5357.
Those are of course allowed through the firewall and since I see the host once I know it works once, just not after for some weird reason and I can't figure it out, it may also be a Windows issue but I actually don't know where I can/should start looking since it works once just not after that.
LLMNR isn't involved here right, since wsdd doesn't include that, am I seeing that right?

**Comment by christgau** [comment]
As I said, you may use wireshark. You can capture the network packets exchanged between the two machines. It would be useful/wise to filter for TCP traffic on port 5357 and (any) udp traffic - as quick'n'dirty attempt. After that you may share the recorded pcap file here for further analysis. But be cautions not to disclose stuff you don't want.

> LLMNR isn't involved here right, since wsdd doesn't include that, am I seeing that right?

True. wsdd does not provide that. Windows however, tries to resolve the machine name once you click/open it in the network view. It tries to resolve the name using LLMNR - along other methods like conventional DNS.

**Comment by black-ish** [comment]
So I checked with Wireshark on Windows and as soon as I start wsdd everything happens how it should, after I click refresh there is absolutely nothing happening on either port 3702 or 5357 really nothing UDP or TCP. There is some activity, of course, on port 138,139 and 445 but nothing else.

**Comment by christgau** [comment]
Ok. Could you check that the "Function Discovery Provider Host" service (fdPHost) on your Windows machine is active?

**Comment by black-ish** [comment]
Yes it is active and running. I can also always see my own machine (client). Which shows up as <computer name> (just redacted that) and the column "Discovery Method" shows "WSD".

**Comment by christgau** [comment]
Mh. Thats really strange. But if no packets are received by the Linux machines (or sent by Windows) then wsdd cannot reply to them which is a fundamental requirement for its purpose. You may try to disable firewalls on both ends and see if a) packets are received on Linux and b) wsdd handles them (try `-vvv` option) and then gradually restrict ports.

**Comment by black-ish** [comment]
Ok I'm appaled to see that even with rules in place that allow it outside the Windows Firewall is blocking something and I don't know why, also it seems that there are more firewall rules necessary in iptables on the Linux host which are very dumb so it seems the communication is weirdly done through ephermeral ports on both sides instead of a static defined one. This is soo bad...
Though it's still weird, I tried that at one point between the Windows client und the VM host and even then it didn't work.
Meh I guess this is solved in a way...
Thank you very much for your help :)
