### ISSUE TITLE
Anounce a machine that is on another ip

### ISSUE THREAD

**Issue by keikop** [christgau/wsdd#33]
Is it possible to use this script to anounce a machine that is on another ip?

**Comment by christgau** [comment]
No, not officially. Vanilla wsdd does not and will not support that. See discussion in https://github.com/christgau/wsdd/issues/21#issuecomment-575760621 for details. I think, however, there are some forks around here which support such a feature.

**Comment by keikop** [comment]
Thanks for the time responding and for the hint. Got a machine on another vlan working.
