### ISSUE TITLE
wsdd fails to start on reboot (Ubuntu 20.04)

### ISSUE THREAD

**Issue by bbdever** [christgau/wsdd#38]
Hi,

Firstly, great work on wsdd. It works flawlessly until reboot when the service fails to start. Reading some of the other posts here, you mentioned trying the branch feat_discovery. So I did that following these steps:

`wget -qO - https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key | sudo apt-key add -`

`echo "deb https://pkg.ltec.ch/public/ bionic main" | sudo tee -a /etc/apt/sources.list.d/ltec.list`

`sudo apt update`

`sudo apt install wsdd`

It works, but I am facing the same problem on reboot where the service fails to start. 

```
● wsdd.service - Web Services Dynamic Discovery host daemon
     Loaded: loaded (/lib/systemd/system/wsdd.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2020-05-08 20:13:51 CEST; 32s ago
    Process: 1383 ExecStart=/usr/bin/wsdd $WSDD_PARAMS (code=exited, status=1/FAILURE)
   Main PID: 1383 (code=exited, status=1/FAILURE)

may 08 20:13:51 ubuntu2004 wsdd[1383]:     self.server_bind()
may 08 20:13:51 ubuntu2004 wsdd[1383]:   File "/usr/bin/wsdd", line 64, in server_bind
may 08 20:13:51 ubuntu2004 wsdd[1383]:     super().server_bind()
may 08 20:13:51 ubuntu2004 wsdd[1383]:   File "/usr/lib/python3.8/http/server.py", line 138, in server_bind
may 08 20:13:51 ubuntu2004 wsdd[1383]:     socketserver.TCPServer.server_bind(self)
may 08 20:13:51 ubuntu2004 wsdd[1383]:   File "/usr/lib/python3.8/socketserver.py", line 466, in server_bind
may 08 20:13:51 ubuntu2004 wsdd[1383]:     self.socket.bind(self.server_address)
may 08 20:13:51 ubuntu2004 wsdd[1383]: OSError: [Errno 99] Cannot assign requested address
may 08 20:13:51 ubuntu2004 systemd[1]: wsdd.service: Main process exited, code=exited, status=1/FAILURE
may 08 20:13:51 ubuntu2004 systemd[1]: wsdd.service: Failed with result 'exit-code'.
```
When I force restart, it works ok again.

`sudo service wsdd restart`

I am using a static IP address:

```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 70:85:c2:7f:40:4e brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.10/24 brd 192.168.1.255 scope global noprefixroute enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::52b9:aa12:7611:b341/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

I'm guessing this is a race issue again? Any ideas?

**Comment by christgau** [comment]
Thanks.

I haven't looked into the package, but I assume the user-contributed Ubuntu/Debian package does not include the development version but an officially released one from the master branch. The version number in the package supports that (https://pkg.ltec.ch/public/pool/main/w/wsdd/). And the master branch version is still affected from the race condition. Nothing has been merged/rebased into master so far.

So, if you want to try the latest version from the development branch (feat/discovery), you have to clone/download it from Github and install it manually. As a quick fix, you can just download the wsdd.py file from the mentioned branch and adjust the path in the service file. Then you should retry and reboot your machine. I assume the problem is gone with the development version.

**Comment by fxrb** [comment]
> I haven't looked into the package, but I assume the user-contributed Ubuntu/Debian package does not include the development version but an officially released one from the master branch. The version number in the package supports that (https://pkg.ltec.ch/public/pool/main/w/wsdd/).<

That's absolutely correct. Once there is new release I will update the package.

regards Felix

**Comment by bbdever** [comment]
Thank you! I have now installed the feat_discovery branch manually from ZIP and the service now starts after reboot.

I do get some warnings but they don't appear to affect the running of wsdd.

```
may 09 16:17:16 ubuntu wsdd[1371]: WARNING: new address 192.168.1.10 on enp1s0
may 09 16:17:17 ubuntu wsdd[1371]: WARNING: new address ::1 on lo
may 09 16:17:17 ubuntu wsdd[1371]: WARNING: ignoring address on lo
may 09 16:17:17 ubuntu wsdd[1371]: /usr/bin/wsdd:1159: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
may 09 16:17:17 ubuntu wsdd[1371]:   logger.warn('ignore address with invalid state {}'.format(
may 09 16:17:17 ubuntu wsdd[1371]: WARNING: ignore address with invalid state 0xc0
may 09 16:17:17 ubuntu wsdd[1371]: WARNING: new address 192.168.1.10 on enp1s0
may 09 16:17:17 ubuntu wsdd[1371]: WARNING: new address 192.168.1.10 on enp1s0
may 09 16:17:18 ubuntu wsdd[1371]: WARNING: new address fe80::52b9:aa12:7611:b341 on enp1s0
may 09 16:17:18 ubuntu wsdd[1371]: WARNING: new address fe80::52b9:aa12:7611:b341 on enp1s0
```

**Comment by christgau** [comment]
Those warnings were intended to assist finding the reason for #34. You can ignore them. There is nothing critical about them as well and they will be removed in future versions. Happy to see that everything else works as expected. Thus, I close this issue.

For the records: State 0xC0 describes a tentative and permanent address. And I strongly assume, that's the IPv6 address is ignored here before it actually used a second later. That's completely fine.
