### ISSUE TITLE
Clarify -d

### ISSUE THREAD

**Issue by amaccuish** [christgau/wsdd#39]
Hi. Cheers for the great software, between this and avahi my network is sorted.

Quick question, for active directory, should I use the DNS domain or the NETBIOS domain name with -d?

**Comment by christgau** [comment]
Thanks.

I have absolutely no idea about AD, but I assume the NETBIOS domain (if there is really such a thing) is not what AD cares about, so I would choose the DNS domain. 

In the end, the `-d` option only changes part of a message exchanged during the host/service discovery. I do not assume that it has further consequences. It might change how the host wsdd is running is grouped in Windows' Network view but Windows will do a name lookup when you double click on that host anyways AFAIK. 

You might test both versions and let the community here know if is has en effect on usability. From my point of view, wsdd provides the means to change information provided according the standard. What you choose and what is best for your network setup is out of the software's scope.

**Comment by christgau** [comment]
does not appear to be a real issue
