### ISSUE TITLE
systemd fail to daemonize

### ISSUE THREAD

**Issue by tkrn** [christgau/wsdd#4]
Using your example systemd script, the service fails to start. See corresponding code and versions below. When ran with the same parameters plus -v, it appears to run as expected interactively.

# python3 -V
Python 3.6.3

# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.6 (Maipo) 

# cat /etc/systemd/system/wsdd.service
```
[Unit]
Description=Web Services Dynamic Discovery host daemon
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/wsdd -i team0
User=nobody
Group=nobody

[Install]
WantedBy=multi-user.target
```

# systemctl status wsdd.service
```
● wsdd.service - Web Services Dynamic Discovery host daemon
   Loaded: loaded (/etc/systemd/system/wsdd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Tue 2019-02-05 00:07:21 EST; 2s ago
  Process: 15656 ExecStart=/usr/bin/wsdd -i team0 (code=exited, status=127)
 Main PID: 15656 (code=exited, status=127)

Feb 05 00:07:21 rhel.local.lan systemd[1]: Started Web Services Dynamic Discovery host daemon.
Feb 05 00:07:21 rhel.local.lan systemd[1]: wsdd.service: main process exited, code=exited, status=127/n/a
Feb 05 00:07:21 rhel.local.lan systemd[1]: Unit wsdd.service entered failed state.
Feb 05 00:07:21 rhel.local.lan systemd[1]: wsdd.service failed.
```

**Comment by christgau** [comment]
Thanks for reporting that issue. 

As you pointed out, the systemd configuration is only an example. This applies to all files found under `etc` in the repo. The reported status code (127) indicates that systemd was not able to locate the command/binary. Please make sure that `/usr/bin/wsdd` really exists and that it is executable. If that is the case please try to launch the program manually with `sudo -u nobody /usr/bin/wsdd -i team0`. If this doesn't run either we'll need to dig deeper.

In addition to that I've read posts of users in the Ubuntu Forums stating that the user/group *nobody* did not exist on their system. Please adjust the user/group to the specifics of your distro/installation. You may also use the generic daemon user/group or create a dedicated user/group for wsdd to enhance security a little.

**Comment by tkrn** [comment]
Thank you. Due to Python3 being a 3rd party supported binary, python3 is not in the default path for RHEL. I modified the script to specifically call that version of python. Thank you for your support. Closing issue.

# cat wsdd.service
```
[Unit]
Description=Web Services Dynamic Discovery host daemon
After=network.target

[Service]
Type=simple
ExecStart=/opt/rh/rh-python36/root/usr/bin/python /usr/bin/wsdd -i team0
User=nobody
Group=nobody

[Install]
WantedBy=multi-user.target
```
