### ISSUE TITLE
UFW Rules

### ISSUE THREAD

**Issue by dwesolowski** [christgau/wsdd#41]
I currently use ufw on Debian 10. How to set rules for the below for my local network? Sorry but new to this.

Both incoming and outgoing multicast traffic on port 3702 must be allowed. For IPv4, the multicast address is 239.255.255.250, for IPv6 the link local SSDP multicast address (fe02::c) is used.

Incoming TCP traffic (and related outgoing traffic) on port 5357 must be allowed.

**Comment by christgau** [comment]
Sorry. The (un)quoted description of the firewall setup from the readme is intentionally a high level description. I can't and won't provide configurations for every firewall or their abstraction interfaces out there. You have to find out how to setup your firewall on your own.  The ufw man page provides some good examples. If you or someone else has found an appropriate rule set, feel free to share it with the community, e.g. by adding a comment here.

**Comment by Fitzcarraldo1** [comment]
I use wsdd in Gentoo Linux and Lubuntu 18.04 with UFW as the firewall. You can read how to configure UFW for wsdd in the section titled 'Step 11. Configure the Linux firewall' of my blog post:

https://fitzcarraldoblog.wordpress.com/2020/06/16/using-ws-discovery-to-enable-windows-10-to-browse-smb-shares-in-my-home-network-of-linux-computers/

**Comment by doctorjames** [comment]
> I use wsdd in Gentoo Linux and Lubuntu 18.04 with UFW as the firewall. You can read how to configure UFW for wsdd in the section titled 'Step 11. Configure the Linux firewall' of my blog post:
> 
> https://fitzcarraldoblog.wordpress.com/2020/06/16/using-ws-discovery-to-enable-windows-10-to-browse-smb-shares-in-my-home-network-of-linux-computers/

That worked great for me on Debian, thanks!
