### ISSUE TITLE
Linux Firewalld services files / A fix for the multiple interface problem with Linux / Problem with deleting interface

### ISSUE THREAD

**Issue by swthemathwiz** [christgau/wsdd#52]
First, let me say that this is a great creation.

I have a couple of firewalld files that might be of interest to those running on Fedora, and the like. The ones that come in the Fedora 32 package do not work (no multicast address). They are xml files can go in /usr/lib/firewalld/services (or /etc/firewalld/services). They are "wsdd.xml" and "wsdd-http.xml" (first includes the second - so just one service to add to the firewall).

On the problems with the bridge/multiple interface issues with Linux, I think the duplication problem is because the kernel does some not so standard stuff with multicast messages, that can be turned off  with a special ioctl (IP_MULTICAST_ALL). The problem is mentioned here:
[Why are multicast messages on the same port but from different groups combined?](https://stackoverflow.com/questions/29833542/why-are-multicast-messages-on-the-same-port-but-from-different-groups-combined)
So I turned off IP_MULTICAST_ALL on the mc listener socket, and and then I can run straight up with multiple interfaces with no duplicate responses.

I put this change in the attached patch file (based on 0.6.1), along with some changes from logger.warn -> logger.warning (obsolete interface). I tested this on my very small vm environment (Fedora 32 (real - 2 interfaces) with Windows 10 (virtual) and Fedora 31 (virtual) seems to work - no dups, Windows sees both Linux machines.

Finally, there's one rare problem that I did run across. Wsdd handles address changes & missing devices nicely, except in the case where one actually deletes the device and recreates it. What seems to happen is that the OS actually does away with the underlying socket. So, when brought up again, even though wsdd will see a new address indication, it's really listening to nothing. To do this correctly, I think you would really have to listen for RTM_DELLINK on the netlink socket, remove the listener, mark the interface dead, probably issue a new Hello when recreated.

Stew

Attached 3 files:

[wsdd.xml.txt](https://github.com/christgau/wsdd/files/4905595/wsdd.xml.txt)
[wsdd-http.xml.txt](https://github.com/christgau/wsdd/files/4905597/wsdd-http.xml.txt)
[wsdd-linux_ip_multicast_all.patch.txt](https://github.com/christgau/wsdd/files/4905598/wsdd-linux_ip_multicast_all.patch.txt)

**Comment by swthemathwiz** [comment]
Oh, I guess the  equivalent change for ipv6 in the init_v6 routine would have IPV6_MULTICAST_ALL = 29. I don't use ipv6, sorry.

**Comment by christgau** [comment]
Thanks for that three-in-one issue ;-) Separate ones or pull requests would have been more appreciated but anyways...

I've fixed the issue with the multicast-all flag and the deprecated warn calls. 

Concerning the firewall configuration: Thanks for that contribution, but firewall configurations will not be included in this project (see #41).

**Comment by swthemathwiz** [comment]
Sorry about that.

Regarding the reason for the IP_MULTICAST_ALL option in Linux, I think at some point they decide they decided to add the option so you can write a simple multicast listener without monitoring all the network interface changes (RTNETLINK, ip changes, etc.). Haven't seen if they have an equivalent multicast sender implementation.

I'll try to get the Fedora people to fix their package with the firewall & systemd.

**Comment by christgau** [comment]
> Sorry about that.

No problem!

> Regarding the reason for the IP_MULTICAST_ALL option in Linux, I think at some point they decide they decided to add the option so you can write a simple multicast listener without monitoring all the network interface changes (RTNETLINK, ip changes, etc.). Haven't seen if they have an equivalent multicast sender implementation.

I see... not that easy to decide how hard a user space program should work to get multicast stuff to work. That 'gimme all multicast messages by default' approach appears to be convenient at first sight but also appears to cause more problems the more I think... Nevertheless, thanks for that explanation.

> I'll try to get the Fedora people to fix their package with the firewall & systemd.

Great. I think this is the right place to address your concerns about firewall stuff.
