### ISSUE TITLE
systemd not starting wsdd

### ISSUE THREAD

**Issue by robertova** [christgau/wsdd#6]
I am using linux mint 19.1. Thes service just works find with the system booted up and the command "sudo systemctl start wsdd". But Systemd throws the following error when started automatically in the boot process:

● wsdd.service - Web Services Dynamic Discovery host daemon
   Loaded: loaded (/etc/systemd/system/wsdd.service; enabled; vendor preset: enabled)
   Active: inactive (dead) since Fri 2019-03-08 10:09:46 CET; 28min ago
  Process: 880 ExecStart=/usr/bin/wsdd -4 -i enp2s0 (code=exited, status=0/SUCCESS)
 Main PID: 880 (code=exited, status=0/SUCCESS)

mar 08 10:09:45 TALLER05 systemd[1]: Started Web Services Dynamic Discovery host daemon.
mar 08 10:09:45 TALLER05 wsdd[880]: 2019-03-08 10:09:45,978:wsdd ERROR(pid 880): No multicast addresses available. Exiting

Do i have to require some other service in wsdd.service file? my service file is:

[Unit]
Description=Web Services Dynamic Discovery host daemon
Requires=network.target
After=network.target

[Service]
Type=simple
ExecStart=/usr/bin/wsdd -4 -i enp2s0
#User=nobody
#Group=nobody

[Install]
WantedBy=multi-user.target

**Comment by christgau** [comment]
Can you start the wsdd service when the system is fully up and running? If so, then the unit file might be changed such that the service depends on a configured network. With the provided example unit file, the daemon may be started when the given network interface does not have an IP address yet. Changing `multi-user.target` to [`network-online.target`](https://www.freedesktop.org/software/systemd/man/systemd.special.html#network-online.target) should work in your setup. Can you check if that works for you?

**Comment by robertova** [comment]
I changed that same error. No multicast addresses available.

Un saludo

**Comment by robertova** [comment]
Excuse me. I was wrong. I changed the unot file and now is working flawessly. The unit file is:

Unit]
Description=Web Services Dynamic Discovery host daemon
Requires=multi-user.target
After=multi-user.target

[Service]
Type=simple
ExecStart=/usr/bin/wsdd -4 -i enp2s0
#User=nobody
#Group=nobody

[Install]
WantedBy=multi-user.target

Problem solved. You can close this issue.

**Comment by christgau** [comment]
Good to hear that you found a solution that works for you. Nevertheless, I tuned the example systemd unit (793a83b8fbeedeb70e2e35fcb1209ed9e55ededf) file in the etc directory to start wsdd after the network becomes was configured.
