### ISSUE TITLE
WSDD service throws error at startup

### ISSUE THREAD

**Issue by daha76** [christgau/wsdd#62]
Hi,

today I found that WSDD service throws error at startup. This is what I get when I run following command:

systemctl status wsdd

and result is:

Oct 10 20:59:45 raspberrypi wsdd[664]:     super().__init__(mch.listen_address, RequestHandlerClass)
Oct 10 20:59:45 raspberrypi wsdd[664]:   File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
Oct 10 20:59:45 raspberrypi wsdd[664]:     self.server_bind()
Oct 10 20:59:45 raspberrypi wsdd[664]:   File "/usr/bin/wsdd", line 805, in server_bind
Oct 10 20:59:45 raspberrypi wsdd[664]:     super().server_bind()
Oct 10 20:59:45 raspberrypi wsdd[664]:   File "/usr/lib/python3.7/http/server.py", line 137, in server_bind
Oct 10 20:59:45 raspberrypi wsdd[664]:     socketserver.TCPServer.server_bind(self)
Oct 10 20:59:45 raspberrypi wsdd[664]:   File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
Oct 10 20:59:45 raspberrypi wsdd[664]:     self.socket.bind(self.server_address)
Oct 10 20:59:45 raspberrypi wsdd[664]: socket.gaierror: [Errno -9] Address family for hostname not supported

I has a latest version of WSDD and I run it on Raspberry Pi 3B+ and Buster.

**Comment by christgau** [comment]
Thanks for the report. I have some questions: What is the command in the systemd unit file you use to start wsdd? Does the error also occur, when you start wsdd on the command line with the exact same arguments? What does the hostname on your machine looks like (`hostname`)?

**Comment by daha76** [comment]
Hi,

so my wsdd.conf looks like this:

`# command line parameters for wsdd (consult man page)
WSDD_PARAMS="-w WORKGROUP"
`

starting from command line is not a problem it it works. Starting it as a service causing already posted error.

That's my finding.

**Comment by christgau** [comment]
Thanks for your analysis. The error messages from the systemd status output indicate a problem in wsdd handles a change in the network configuration, i.e. an address removal. This may happen on system startup when the wifi receives an address (via DHCP or SLAAC, e.g.) and drops an old one in favor for the new one. I'll look into this...

**Comment by christgau** [comment]
Ok, you actually faced two issues here. The one in your original post was encountered when new addresses are added, and the second one occurred when addresses are removed. Both of the issues are should be resolved within the [issue-62](/christgau/wsdd/tree/issue-62) branch. Could give that a try?

**Comment by daha76** [comment]
OK, I can test it, but is it enough just to make an update via apt or the procedure to get the isue-62 branch is different?

**Comment by christgau** [comment]
>  is it enough just to make an update via apt 

No.

> or the procedure to get the isue-62 branch is different?

Yes. Please do the following

1. Download the wsdd.py with the latest patches from https://raw.githubusercontent.com/christgau/wsdd/issue-62/src/wsdd.py
2. Locate where the wsdd script is currently installed. I suspect it is `/usr/bin/wsdd` (based on your systemctl output)
3. Replace the file from step 2 with the downloaded file from step 1.
4. Restart your system and check whether the error still occurs.

**Comment by daha76** [comment]
Ok I will test it and let you know.

**Comment by daha76** [comment]
So it looks like now it works even after restart, so from my point of view this bug is fixed ;-) Thanks.

**Comment by christgau** [comment]
Thanks to you for testing. Pushed the fixes into the master branch an released a new version (together with other fixes).
