### ISSUE TITLE
how to add the repo and key to ubuntu (lubuntu and Raspian)

### ISSUE THREAD

**Issue by bjlockie** [christgau/wsdd#64]
$ sudo -s
$ echo "deb https://pkg.ltec.ch/public/ " `lsb_release -c | cut -f2` " main" >> /etc/apt/sources.list
$ apt-key adv --fetch-keys https://pkg.ltec.ch/public/conf/ltec-ag.gpg.key
$ apt update
$ apt install wsdd
$ service wsdd start

**Comment by christgau** [comment]
Sorry, but what it is the actual issue here? I do not have a Debian-based system at hand where I can test your commands.

BTW, formatting them with triple back ticks in the markdown would ease the readability.

**Comment by fxrb** [comment]
As there is no question mark ending the title, I can just guess that the author tried to share his experience with installing wsdd on his own system. At least that's what a deep look into my crystal boll told me.

**Comment by bjlockie** [comment]
Correct, it is just informational.

**Comment by christgau** [comment]
Well, then why open an issue if there is none? Please don't do this. 

Nevertheless, the Readme already includes steps for installing wsdd on a Debian-bases distro. If there is something missing, feel free an open an PR that adds the missing information.
