### ISSUE TITLE
ARM / ARM64 binaries

### ISSUE THREAD

**Issue by gemignani** [christgau/wsdd#65]
Hi there,
Many thanks for the project.
Would you please be kind to compile the projects with for usual arm targets? I'm currently using a ubuntu 20.04 on pi4, but those bins are not present in your host.

Skipping acquire of configured file 'main/binary-arm64/Packages' as repository 'https://pkg.ltec.ch/public focal InRelease' doesn't support architecture 'arm64'

Please note that the python script works fine for me.

**Comment by christgau** [comment]
This was just recently discussed under [another issue](https://github.com/christgau/wsdd/issues/19#issuecomment-719913217). Have a look there. Please also note that wsdd is always just a Python script. No binaries are built for for whatever architecture at least from my side. Only packages are contributed by other people which do basically nothing more installing the script and some service wrappers, AFAIK. If you have trouble with the packages, please make a comment in #19.
