### ISSUE TITLE
allow announcement of a host not inside the same broadcast domain

### ISSUE THREAD

**Issue by mercora** [christgau/wsdd#68]
afaict it is currently not possible to announce a host that is not the one running this service. I would like to do this in order to make a samba server discoverable which is not on the same broadcast domain. i have not looked into this really but it appears that this should be possible but might require the service to be running on the announced host too. would you consider including such a change?

**Comment by mercora** [comment]
nvm i just read the other closed issues about this...

**Comment by christgau** [comment]
Would you mind to share your findings? 

> it is currently not possible to announce a host that is not the one running this service

That's indeed possible. You can start wsdd with (any) another hostname. See the option with that name. In addition you need DNS (or LLMNR) to resolve the hostname to the correct IP. However, this is not really what wsdd is supposed to do. And what definitely is not working is announcing _multiple_ hosts.

**Comment by mercora** [comment]
i was mostly reffering to #21. but i would really not mind running multiple instances if that is possible. I was assuming clients might assume the address sending the announcements is the host they should connect to (via unicast) or similar issues.

If i understand it correctly, it does not really matter as long as the announcement refers to a hostname resolvable via DNS (or LLMNR). Also these announcement and probes use multicast and therefore there is no issue with running multiple instances?

**Comment by christgau** [comment]
> If i understand it correctly, it does not really matter 

Yes. Windows does not care about the announced name until you try to open it. At this point it tries to use the displayed/discovered name to connect to it...

> as long as the announcement refers to a hostname resolvable via DNS (or LLMNR).

Yes... and no 😉 You can even supply any IP: `wsdd --hostname 192.168.42.42` If 192.168.42.42 is reachable by windows it will connect to that host, not the one that runs wsdd. But, honestly, it is not a good to do so...

> Also these announcement and probes use multicast 

During the discovery process, both multicast and unicast are used - depending on the side you are looking at: https://docs.microsoft.com/en-us/windows/win32/wsdapi/discovery-and-metadata-exchange-message-patterns

> and therefore there is no issue with running multiple instances?

Not sure what you mean by "issues with multiple instances", but running multiple instances (on the same interface) is not supported.

**Comment by mercora** [comment]
> Not sure what you mean by "issues with multiple instances", but running multiple instances (on the same interface) is not supported.

If only probes were to be received via multicast this service would only need to be bound to this multicast address and therefore any other socket could receive the same probes using the same interface on the same machine simultaneously. But apparently this requires listening on unicast addresses too (for the Get metadata flow) which would be hard to do using 2 or more separate processes on the same machine, address and interface. So now i even know why :)

I am sorry for bothering you with this as obviously i could have figured this out myself,  i should have researched a bit before creating this issue. and thanks for taking your time with this anyhow.
