### ISSUE TITLE
netbios aliases

### ISSUE THREAD

**Issue by pol-hallen** [christgau/wsdd#73]
Hi all :+1: 

adding "netbios aliases" in smb.conf the directive:

```
netbios name = srv0
netbios aliases = srv1 srv2 srv3 srv4

```
from win10 clients I see only srv0 although I can ping srv1 and so on

is it a bug? thanks

Pol

**Comment by christgau** [comment]
wsdd by itself does not interact with Samba and Samba's configuration. Such an "interaction" is done by some init-scripts and also depends on the OS/distribution in use. However, I am not aware of any solution that checks for the `netbios name` in the Samba configuration. It might be a coincidence that in your environment the configured `netbios name` matches the hostname which wsdd picks up by default. In a nutshell: changing the Samba configuration does not affect wsdd at all. 

That being said, there is also no interplay between the Samba config when it comes to ` netbios aliases` - at least form the source code perspective. Additionally, wsdd does not support announcing multiple host names. As a consequence, even if one would parse the Samba config and look for the aliases there is no way of telling wsdd about them. So there is no bug, there is (currently) no possibility to do what you want. 

Finally, I don't see a reason for announcing the same server under five different names.
