### ISSUE TITLE
Cups printers not showing up

### ISSUE THREAD

**Issue by hpapagaj** [christgau/wsdd#78]
Hi,

Great project. I had problems discovering my Linux shares on Windows clients, but with wsdd they are showing up instantly.

<img width="372" alt="Screenshot 2021-01-20 at 00 28 49" src="https://user-images.githubusercontent.com/72989831/105106603-8103f500-5ab6-11eb-86d1-82a2bdc18477.png">

There is just one thing not working: my shared printers on Linux are not showing up. In CUPS I have it shared, in samba I have:

```
[printers]
   comment = All Printers
   browseable = yes
   path = /var/spool/samba
   printable = yes
   guest ok = yes
   read only = no
   create mask = 0700
```

They should be discoverable with wsdd or not?

**Comment by christgau** [comment]
Thanks.

Short answer to your question: No. 

Long answer: wsdd is designed to only advertise the Samba host as a computer on the the local network. From a quick look into the specs, it looks like it would be possible to announce printers as well. However, it appears to me that it leads to more challenges and would solve a problem that is already solved. If you click on a host in Windows' "Network" view and the host offers printers, the printers are listed. Thus, you are to find the printer. Note that Samba also takes care of things like which user (or even guest) is allowed to see that printer. If you have a Linux or MacOS system you are probably able to find the printer with the help of Avahi/Zeroconf which is supported by CUPS natively. Consequently, you are able to find a printer on most OS without knowing the name. 

Ideally your printer would be a network printer on its own (without need for CUPS) and it would support WSD directly so there would be no need for a "kludge solution" using wsdd 😉

Note: There was a WSD implementation around which allowed to specify the model and maybe the device profile, but I cant find it right now. You could play around with that to announce a local printer via WSD.
