### ISSUE TITLE
WSDD 0.6.3 breaks on Raspian Buster

### ISSUE THREAD

**Issue by BlowflyOZ** [christgau/wsdd#82]
After upgrade from 0.6.2 to 0.6.3 all WSDD stops functioning. 

Rolling back requires apt get purge before downgrading to the 0.6.2 debian package to get functionality back.

**Comment by christgau** [comment]
The Problem might be related to #80, but my testing on Linux did not show that 0.6.3 is affected on Linux. At least not my installation(s) with kernel 5.4.48. Nevertheless, could you check whether the version from the [issue branch ](https://github.com/christgau/wsdd/tree/issue-80) works for you?

**Comment by BlowflyOZ** [comment]
so just replace the wsdd.py with #80 version to test ?

**Comment by christgau** [comment]
>so just replace the wsdd.py with #80 version to test ?

Correct.

**Comment by BlowflyOZ** [comment]
Thankyou yes, I have replaced the 0.6.2 package script with your #80 version and after a reboot it seems to be working again. 
I assume this will roll up into the next package as some stage? (as I don't want to break it again with the next update?)

**Comment by christgau** [comment]
Ok, great. Thanks for testing. 

I think I'll release a new as soon as there is feedback from the FreeBSD community on #80. Despite for Gentoo, I do not create packages. Others thankfully do this and I'm sure they will release new packages as well shortly after a release here.

**Comment by christgau** [comment]
Has been solved, see #80
