### ISSUE TITLE
Can't get samba/cifs share seen in Windows XP (!)

### ISSUE THREAD

**Issue by brianread108** [christgau/wsdd#90]
I am running a local copy of Windows XP for legacy reasons, and trying to get it to connect to openmediavault, which runs wsdd.
However I not having any luck so far. The Samba shares are easily seen by Win10. 
Anyone got any thoughts?

**Comment by christgau** [comment]
IIRC, support for the Webservice Discovery protocol was added with Windows 7, maybe Vista. Wsdd cannot do something here. 

I think that you may need to explicitly enable older (and unsafe) Samba protocol versions for supporting Windows XP. Maybe netbios support must also be enabled on the Samba site.
