### ISSUE TITLE
The [wsdd] repository does not have a Release file

### ISSUE THREAD

**Issue by FlexMcMurphy** [christgau/wsdd#91]
Hello,

I am using Raspbian Stretch on a Pi 3 B+.

I added a file with this line:
`deb https://pkg.ltec.ch/public/ stretch main`

To..
`/etc/apt/sources.list.d/wsdd.list`

But I get this when I do `apt update`

```
root@NEXTCLOUDPI:/etc/apt/sources.list.d# apt update
Hit:1 http://raspbian.raspberrypi.org/raspbian stretch InRelease
Get:2 http://archive.raspberrypi.org/debian stretch InRelease [25.3 kB]
Ign:3 https://pkg.ltec.ch/public stretch InRelease
Err:4 https://pkg.ltec.ch/public stretch Release
  404  Not Found
Reading package lists... Done
E: The repository 'https://pkg.ltec.ch/public stretch Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```
How do I fix this? Is there another way to install wsdd?

Cheers,

**Comment by fxrb** [comment]
Although _Debian stretch_ is passed EOL i have added it to the repository. Just try again and it should work.
I strongly suggest you **update your system** to the current stable _Debian 10_ known as _buster_.
Last but not least: if everything fails you can still install from source as _wsdd_ is a python script.

**Comment by FlexMcMurphy** [comment]
Thanks very much indeed.

Yes I see now the generic installation instructions explain how to install the python script manually,

**Comment by christgau** [comment]
Not really an issue of wsdd on its own and the release file has been added in the meanwhile. I suppose the issue has been resolved. Closing it...
